// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_CalibrationAdvancedText;
lv_obj_t * uic_CalibrationAdvanced;
lv_obj_t * uic_CalibrationLongitudes;
lv_obj_t * uic_LatitudesText;
lv_obj_t * uic_CalibrationLatitudes;
lv_obj_t * uic_CalibrationSetAsZeroText;
lv_obj_t * uic_CalibrationSetAsZero;
lv_obj_t * uic_CalibrationInstruction;
lv_obj_t * uic_CalibrationRawCoord;
lv_obj_t * uic_CalibrateFooter;
lv_obj_t * uic_CalibrationScreen;
lv_obj_t * ui_CalibrationScreen = NULL;
lv_obj_t * ui_HomeButton2 = NULL;
lv_obj_t * ui_CalibrateFooter = NULL;
lv_obj_t * ui_CalibrationRawCoord = NULL;
lv_obj_t * ui_CalibrationInstruction = NULL;
lv_obj_t * ui_CalibrationSetAsZero = NULL;
lv_obj_t * ui_CalibrationSetAsZeroText = NULL;
lv_obj_t * ui_CalibrationLatitudes = NULL;
lv_obj_t * ui_LatitudesText = NULL;
lv_obj_t * ui_CalibrationLongitudes = NULL;
lv_obj_t * ui_LongitudesText = NULL;
lv_obj_t * ui_CalibrationAdvanced = NULL;
lv_obj_t * ui_CalibrationAdvancedText = NULL;
// event funtions
void ui_event_HomeButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
        beep(e);
    }
}

void ui_event_CalibrationSetAsZero(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        CalibrationSetAsZero(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        CalibrationSetAsZero(e);
    }
}

void ui_event_CalibrationLatitudes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CalibrationLatitudes(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        CalibrationLatitudes(e);
    }
}

void ui_event_CalibrationLongitudes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CalibrationLongitudes(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        CalibrationLongitudes(e);
    }
}

void ui_event_CalibrationAdvanced(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CalibrationAdvanced(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        CalibrationAdvanced(e);
    }
}

// build funtions

void ui_CalibrationScreen_screen_init(void)
{
    ui_CalibrationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton2 = lv_img_create(ui_CalibrationScreen);
    lv_img_set_src(ui_HomeButton2, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton2, 0);
    lv_obj_set_y(ui_HomeButton2, 195);
    lv_obj_set_align(ui_HomeButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_HomeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_CalibrateFooter = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrateFooter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrateFooter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrateFooter, 0);
    lv_obj_set_y(ui_CalibrateFooter, -190);
    lv_obj_set_align(ui_CalibrateFooter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrateFooter, "Raw Globe Location");
    lv_obj_set_style_text_align(ui_CalibrateFooter, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrateFooter, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationRawCoord = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationRawCoord, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationRawCoord, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationRawCoord, 0);
    lv_obj_set_y(ui_CalibrationRawCoord, -150);
    lv_obj_set_align(ui_CalibrationRawCoord, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationRawCoord, "N00.0  -  W00.0");
    lv_obj_clear_flag(ui_CalibrationRawCoord,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_CalibrationRawCoord, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationRawCoord, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationInstruction = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationInstruction, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_CalibrationInstruction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationInstruction, 0);
    lv_obj_set_y(ui_CalibrationInstruction, 150);
    lv_obj_set_align(ui_CalibrationInstruction, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_CalibrationInstruction, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_CalibrationInstruction, "Long Press Button To Select");
    lv_obj_set_style_text_font(ui_CalibrationInstruction, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationSetAsZero = lv_btn_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationSetAsZero, 200);
    lv_obj_set_height(ui_CalibrationSetAsZero, 50);
    lv_obj_set_x(ui_CalibrationSetAsZero, 0);
    lv_obj_set_y(ui_CalibrationSetAsZero, -90);
    lv_obj_set_align(ui_CalibrationSetAsZero, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationSetAsZero, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationSetAsZero, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationSetAsZero, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationSetAsZero, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_CalibrationSetAsZeroText = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationSetAsZeroText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationSetAsZeroText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationSetAsZeroText, 0);
    lv_obj_set_y(ui_CalibrationSetAsZeroText, -90);
    lv_obj_set_align(ui_CalibrationSetAsZeroText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationSetAsZeroText, "SET AS ZERO");
    lv_obj_set_style_text_color(ui_CalibrationSetAsZeroText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationSetAsZeroText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CalibrationSetAsZeroText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationSetAsZeroText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationLatitudes = lv_btn_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationLatitudes, 200);
    lv_obj_set_height(ui_CalibrationLatitudes, 50);
    lv_obj_set_x(ui_CalibrationLatitudes, 0);
    lv_obj_set_y(ui_CalibrationLatitudes, -30);
    lv_obj_set_align(ui_CalibrationLatitudes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationLatitudes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationLatitudes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationLatitudes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationLatitudes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_LatitudesText = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_LatitudesText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LatitudesText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LatitudesText, 0);
    lv_obj_set_y(ui_LatitudesText, -30);
    lv_obj_set_align(ui_LatitudesText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LatitudesText, "LATTITUDES");
    lv_obj_set_style_text_color(ui_LatitudesText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LatitudesText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LatitudesText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LatitudesText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationLongitudes = lv_btn_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationLongitudes, 200);
    lv_obj_set_height(ui_CalibrationLongitudes, 50);
    lv_obj_set_x(ui_CalibrationLongitudes, 0);
    lv_obj_set_y(ui_CalibrationLongitudes, 30);
    lv_obj_set_align(ui_CalibrationLongitudes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationLongitudes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationLongitudes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationLongitudes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationLongitudes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_LongitudesText = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_LongitudesText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LongitudesText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LongitudesText, 0);
    lv_obj_set_y(ui_LongitudesText, 30);
    lv_obj_set_align(ui_LongitudesText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LongitudesText, "LONGITUDES");
    lv_obj_set_style_text_color(ui_LongitudesText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LongitudesText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LongitudesText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LongitudesText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationAdvanced = lv_btn_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationAdvanced, 200);
    lv_obj_set_height(ui_CalibrationAdvanced, 50);
    lv_obj_set_x(ui_CalibrationAdvanced, 0);
    lv_obj_set_y(ui_CalibrationAdvanced, 90);
    lv_obj_set_align(ui_CalibrationAdvanced, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationAdvanced, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationAdvanced, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationAdvanced, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationAdvanced, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_CalibrationAdvancedText = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationAdvancedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationAdvancedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationAdvancedText, 0);
    lv_obj_set_y(ui_CalibrationAdvancedText, 90);
    lv_obj_set_align(ui_CalibrationAdvancedText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationAdvancedText, "ADVANCED");
    lv_obj_set_style_text_color(ui_CalibrationAdvancedText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationAdvancedText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CalibrationAdvancedText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationAdvancedText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton2, ui_event_HomeButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationSetAsZero, ui_event_CalibrationSetAsZero, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationLatitudes, ui_event_CalibrationLatitudes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationLongitudes, ui_event_CalibrationLongitudes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationAdvanced, ui_event_CalibrationAdvanced, LV_EVENT_ALL, NULL);
    uic_CalibrationScreen = ui_CalibrationScreen;
    uic_CalibrateFooter = ui_CalibrateFooter;
    uic_CalibrationRawCoord = ui_CalibrationRawCoord;
    uic_CalibrationInstruction = ui_CalibrationInstruction;
    uic_CalibrationSetAsZero = ui_CalibrationSetAsZero;
    uic_CalibrationSetAsZeroText = ui_CalibrationSetAsZeroText;
    uic_CalibrationLatitudes = ui_CalibrationLatitudes;
    uic_LatitudesText = ui_LatitudesText;
    uic_CalibrationLongitudes = ui_CalibrationLongitudes;
    uic_CalibrationAdvanced = ui_CalibrationAdvanced;
    uic_CalibrationAdvancedText = ui_CalibrationAdvancedText;

}

void ui_CalibrationScreen_screen_destroy(void)
{
    if(ui_CalibrationScreen) lv_obj_del(ui_CalibrationScreen);

    // NULL screen variables
    uic_CalibrationScreen = NULL;
    ui_CalibrationScreen = NULL;
    ui_HomeButton2 = NULL;
    uic_CalibrateFooter = NULL;
    ui_CalibrateFooter = NULL;
    uic_CalibrationRawCoord = NULL;
    ui_CalibrationRawCoord = NULL;
    uic_CalibrationInstruction = NULL;
    ui_CalibrationInstruction = NULL;
    uic_CalibrationSetAsZero = NULL;
    ui_CalibrationSetAsZero = NULL;
    uic_CalibrationSetAsZeroText = NULL;
    ui_CalibrationSetAsZeroText = NULL;
    uic_CalibrationLatitudes = NULL;
    ui_CalibrationLatitudes = NULL;
    uic_LatitudesText = NULL;
    ui_LatitudesText = NULL;
    uic_CalibrationLongitudes = NULL;
    ui_CalibrationLongitudes = NULL;
    ui_LongitudesText = NULL;
    uic_CalibrationAdvanced = NULL;
    ui_CalibrationAdvanced = NULL;
    uic_CalibrationAdvancedText = NULL;
    ui_CalibrationAdvancedText = NULL;

}
