// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_SpinLock;
lv_obj_t * uic_CalToStored;
lv_obj_t * uic_CalFromRaw;
lv_obj_t * uic_TriangleTo;
lv_obj_t * uic_TriangleFrom;
lv_obj_t * uic_RollerNS;
lv_obj_t * uic_RollerEW;
lv_obj_t * uic_CalibrationPointText;
lv_obj_t * uic_CalibrationPoint;
lv_obj_t * uic_CalibrationAdvInstruction;
lv_obj_t * uic_CalibrationAdvGps;
lv_obj_t * uic_CalibrationAdvHeader;
lv_obj_t * uic_CalibrationScreenAdvanced;
lv_obj_t * ui_CalibrationScreenAdvanced = NULL;
lv_obj_t * ui_HomeButton1 = NULL;
lv_obj_t * ui_CalibrationAdvHeader = NULL;
lv_obj_t * ui_CalibrationAdvGps = NULL;
lv_obj_t * ui_CalibrationAdvInstruction = NULL;
lv_obj_t * ui_CalibrationPoint = NULL;
lv_obj_t * ui_CalibrationPointText = NULL;
lv_obj_t * ui_RollerEW = NULL;
lv_obj_t * ui_RollerNS = NULL;
lv_obj_t * ui_TriangleFrom = NULL;
lv_obj_t * ui_TriangleTo = NULL;
lv_obj_t * ui_CalFromRaw = NULL;
lv_obj_t * ui_CalToStored = NULL;
lv_obj_t * ui_SpinLock = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_HomeButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
        beep(e);
    }
}

void ui_event_CalibrationPoint(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CalibratePoint(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        CalibratePoint(e);
    }
}

void ui_event_RollerEW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        RollerNSorEWChanged(e);
    }
}

void ui_event_RollerNS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        RollerNSorEWChanged(e);
    }
}

// build funtions

void ui_CalibrationScreenAdvanced_screen_init(void)
{
    ui_CalibrationScreenAdvanced = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalibrationScreenAdvanced, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton1 = lv_img_create(ui_CalibrationScreenAdvanced);
    lv_img_set_src(ui_HomeButton1, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton1, 0);
    lv_obj_set_y(ui_HomeButton1, 195);
    lv_obj_set_align(ui_HomeButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_CalibrationAdvHeader = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_CalibrationAdvHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationAdvHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationAdvHeader, 0);
    lv_obj_set_y(ui_CalibrationAdvHeader, -190);
    lv_obj_set_align(ui_CalibrationAdvHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationAdvHeader, "Globe Location");
    lv_obj_set_style_text_align(ui_CalibrationAdvHeader, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationAdvHeader, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationAdvGps = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_CalibrationAdvGps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationAdvGps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationAdvGps, 0);
    lv_obj_set_y(ui_CalibrationAdvGps, -157);
    lv_obj_set_align(ui_CalibrationAdvGps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationAdvGps, "N00.0  -  W00.0");
    lv_obj_clear_flag(ui_CalibrationAdvGps,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationAdvGps, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationAdvGps, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_turquoise);
    lv_obj_set_style_text_align(ui_CalibrationAdvGps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationAdvGps, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationAdvInstruction = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_CalibrationAdvInstruction, 327);
    lv_obj_set_height(ui_CalibrationAdvInstruction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationAdvInstruction, 0);
    lv_obj_set_y(ui_CalibrationAdvInstruction, -127);
    lv_obj_set_align(ui_CalibrationAdvInstruction, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_CalibrationAdvInstruction, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_CalibrationAdvInstruction,
                      "Postion Globe To Chosen Location   ---   Long Press Button To Confirm   ---");
    lv_obj_set_style_text_font(ui_CalibrationAdvInstruction, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationPoint = lv_btn_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_CalibrationPoint, 200);
    lv_obj_set_height(ui_CalibrationPoint, 50);
    lv_obj_set_align(ui_CalibrationPoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationPoint, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationPoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationPoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationPoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_CalibrationPointText = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_CalibrationPointText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationPointText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrationPointText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationPointText, "CALIBRATE");
    lv_obj_add_state(ui_CalibrationPointText, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_color(ui_CalibrationPointText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationPointText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CalibrationPointText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationPointText, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CalibrationPointText, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_CalibrationPointText, 128, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_RollerEW = lv_roller_create(ui_CalibrationScreenAdvanced);
    lv_roller_set_options(ui_RollerEW,
                          "W-180\nW-165\nW-150\nW-135\nW-120\nW-105\nW-90\nW-75\nW-60\nW-45\nW-30\nW-15\nE-0\nE-15\nE-30\nE-45\nE-60\nE-75\nE-90\nE-105\nE-120\nE-135\nE-150\nE-165\nE-180",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerEW, 12, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerEW, 120);
    lv_obj_set_height(ui_RollerEW, 145);
    lv_obj_set_x(ui_RollerEW, 165);
    lv_obj_set_y(ui_RollerEW, 0);
    lv_obj_set_align(ui_RollerEW, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerEW, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerNS = lv_roller_create(ui_CalibrationScreenAdvanced);
    lv_roller_set_options(ui_RollerNS, "N-75\nN-60\nN-45\nN-30\nN-15\nN-0\nS-0\nS-15\nS-30\nS-45\nS-60\nS-75",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerNS, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerNS, 120);
    lv_obj_set_height(ui_RollerNS, 145);
    lv_obj_set_x(ui_RollerNS, -165);
    lv_obj_set_y(ui_RollerNS, 0);
    lv_obj_set_align(ui_RollerNS, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerNS, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TriangleFrom = lv_img_create(ui_CalibrationScreenAdvanced);
    lv_img_set_src(ui_TriangleFrom, &ui_img_triangle_down_16x16_png);
    lv_obj_set_width(ui_TriangleFrom, 16);
    lv_obj_set_height(ui_TriangleFrom, 16);
    lv_obj_set_x(ui_TriangleFrom, 0);
    lv_obj_set_y(ui_TriangleFrom, -36);
    lv_obj_set_align(ui_TriangleFrom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TriangleFrom, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TriangleFrom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TriangleFrom, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_TriangleFrom, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_TriangleTo = lv_img_create(ui_CalibrationScreenAdvanced);
    lv_img_set_src(ui_TriangleTo, &ui_img_triangle_down_16x16_png);
    lv_obj_set_width(ui_TriangleTo, 16);
    lv_obj_set_height(ui_TriangleTo, 16);
    lv_obj_set_x(ui_TriangleTo, 0);
    lv_obj_set_y(ui_TriangleTo, 37);
    lv_obj_set_align(ui_TriangleTo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TriangleTo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TriangleTo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TriangleTo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_TriangleTo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_CalFromRaw = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_CalFromRaw, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalFromRaw, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalFromRaw, 0);
    lv_obj_set_y(ui_CalFromRaw, -55);
    lv_obj_set_align(ui_CalFromRaw, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalFromRaw, "N00.0  -  W00.0");
    lv_obj_set_style_text_font(ui_CalFromRaw, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalToStored = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_CalToStored, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalToStored, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalToStored, 0);
    lv_obj_set_y(ui_CalToStored, 55);
    lv_obj_set_align(ui_CalToStored, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalToStored, "N00.0  -  W00.0");
    lv_obj_set_style_text_font(ui_CalToStored, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinLock = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_SpinLock, 327);
    lv_obj_set_height(ui_SpinLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpinLock, 0);
    lv_obj_set_y(ui_SpinLock, 110);
    lv_obj_set_align(ui_SpinLock, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SpinLock, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_SpinLock, "Helpful Hint");
    lv_obj_set_style_text_align(ui_SpinLock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinLock, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -77);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "(RAW)");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_CalibrationScreenAdvanced);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 78);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "(STORED)");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationPoint, ui_event_CalibrationPoint, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerEW, ui_event_RollerEW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerNS, ui_event_RollerNS, LV_EVENT_ALL, NULL);
    uic_CalibrationScreenAdvanced = ui_CalibrationScreenAdvanced;
    uic_CalibrationAdvHeader = ui_CalibrationAdvHeader;
    uic_CalibrationAdvGps = ui_CalibrationAdvGps;
    uic_CalibrationAdvInstruction = ui_CalibrationAdvInstruction;
    uic_CalibrationPoint = ui_CalibrationPoint;
    uic_CalibrationPointText = ui_CalibrationPointText;
    uic_RollerEW = ui_RollerEW;
    uic_RollerNS = ui_RollerNS;
    uic_TriangleFrom = ui_TriangleFrom;
    uic_TriangleTo = ui_TriangleTo;
    uic_CalFromRaw = ui_CalFromRaw;
    uic_CalToStored = ui_CalToStored;
    uic_SpinLock = ui_SpinLock;

}

void ui_CalibrationScreenAdvanced_screen_destroy(void)
{
    if(ui_CalibrationScreenAdvanced) lv_obj_del(ui_CalibrationScreenAdvanced);

    // NULL screen variables
    uic_CalibrationScreenAdvanced = NULL;
    ui_CalibrationScreenAdvanced = NULL;
    ui_HomeButton1 = NULL;
    uic_CalibrationAdvHeader = NULL;
    ui_CalibrationAdvHeader = NULL;
    uic_CalibrationAdvGps = NULL;
    ui_CalibrationAdvGps = NULL;
    uic_CalibrationAdvInstruction = NULL;
    ui_CalibrationAdvInstruction = NULL;
    uic_CalibrationPoint = NULL;
    ui_CalibrationPoint = NULL;
    uic_CalibrationPointText = NULL;
    ui_CalibrationPointText = NULL;
    uic_RollerEW = NULL;
    ui_RollerEW = NULL;
    uic_RollerNS = NULL;
    ui_RollerNS = NULL;
    uic_TriangleFrom = NULL;
    ui_TriangleFrom = NULL;
    uic_TriangleTo = NULL;
    ui_TriangleTo = NULL;
    uic_CalFromRaw = NULL;
    ui_CalFromRaw = NULL;
    uic_CalToStored = NULL;
    ui_CalToStored = NULL;
    uic_SpinLock = NULL;
    ui_SpinLock = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;

}
