// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_CalibrationSetButton;
lv_obj_t * uic_GPS_Coordinate_Cal;
lv_obj_t * uic_CalibrateInstruction;
lv_obj_t * uic_CalibrationButtonNextText;
lv_obj_t * uic_CalibrationNextButton;
lv_obj_t * uic_CalibrationScreen;
lv_obj_t * ui_CalibrationScreen;
lv_obj_t * ui_HomeButton2;
lv_obj_t * ui_CalibrationNextButton;
lv_obj_t * ui_CalibrationButtonNextText;
lv_obj_t * ui_CalibrateInstruction;
lv_obj_t * ui_GPS_Coordinate_Cal;
lv_obj_t * ui_CalibrationSetButton;
lv_obj_t * ui_CalibrationButtonNextText1;

// event funtions
void ui_event_HomeButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_CalibrationNextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CalibrationNextButton(e);
    }
}

void ui_event_CalibrationSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CalibrationSetButton(e);
    }
}

// build funtions

void ui_CalibrationScreen_screen_init(void)
{
    ui_CalibrationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton2 = lv_img_create(ui_CalibrationScreen);
    lv_img_set_src(ui_HomeButton2, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton2, 0);
    lv_obj_set_y(ui_HomeButton2, 168);
    lv_obj_set_align(ui_HomeButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_HomeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_yellow);

    ui_CalibrationNextButton = lv_btn_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationNextButton, 200);
    lv_obj_set_height(ui_CalibrationNextButton, 50);
    lv_obj_set_x(ui_CalibrationNextButton, 0);
    lv_obj_set_y(ui_CalibrationNextButton, 46);
    lv_obj_set_align(ui_CalibrationNextButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationNextButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationNextButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationNextButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_CalibrationNextButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_CalibrationButtonNextText = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationButtonNextText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationButtonNextText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationButtonNextText, 0);
    lv_obj_set_y(ui_CalibrationButtonNextText, 46);
    lv_obj_set_align(ui_CalibrationButtonNextText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationButtonNextText, "NEXT");
    lv_obj_set_style_text_color(ui_CalibrationButtonNextText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationButtonNextText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CalibrationButtonNextText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationButtonNextText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrateInstruction = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrateInstruction, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrateInstruction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrateInstruction, 0);
    lv_obj_set_y(ui_CalibrateInstruction, -116);
    lv_obj_set_align(ui_CalibrateInstruction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrateInstruction, "INSTRUCTION");
    lv_obj_set_style_text_align(ui_CalibrateInstruction, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrateInstruction, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Coordinate_Cal = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_GPS_Coordinate_Cal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Coordinate_Cal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Coordinate_Cal, 0);
    lv_obj_set_y(ui_GPS_Coordinate_Cal, -145);
    lv_obj_set_align(ui_GPS_Coordinate_Cal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPS_Coordinate_Cal, "N00.0  -  W00.0");
    lv_obj_clear_flag(ui_GPS_Coordinate_Cal,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_GPS_Coordinate_Cal, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_GPS_Coordinate_Cal, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellow);
    lv_obj_set_style_text_align(ui_GPS_Coordinate_Cal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPS_Coordinate_Cal, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationSetButton = lv_btn_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationSetButton, 200);
    lv_obj_set_height(ui_CalibrationSetButton, 50);
    lv_obj_set_x(ui_CalibrationSetButton, 0);
    lv_obj_set_y(ui_CalibrationSetButton, -36);
    lv_obj_set_align(ui_CalibrationSetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationSetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationSetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationSetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_CalibrationSetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_CalibrationButtonNextText1 = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_CalibrationButtonNextText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationButtonNextText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationButtonNextText1, 0);
    lv_obj_set_y(ui_CalibrationButtonNextText1, -36);
    lv_obj_set_align(ui_CalibrationButtonNextText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationButtonNextText1, "SET");
    lv_obj_set_style_text_color(ui_CalibrationButtonNextText1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationButtonNextText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CalibrationButtonNextText1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationButtonNextText1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton2, ui_event_HomeButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationNextButton, ui_event_CalibrationNextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationSetButton, ui_event_CalibrationSetButton, LV_EVENT_ALL, NULL);
    uic_CalibrationScreen = ui_CalibrationScreen;
    uic_CalibrationNextButton = ui_CalibrationNextButton;
    uic_CalibrationButtonNextText = ui_CalibrationButtonNextText;
    uic_CalibrateInstruction = ui_CalibrateInstruction;
    uic_GPS_Coordinate_Cal = ui_GPS_Coordinate_Cal;
    uic_CalibrationSetButton = ui_CalibrationSetButton;

}

void ui_CalibrationScreen_screen_destroy(void)
{
    if(ui_CalibrationScreen) lv_obj_del(ui_CalibrationScreen);

    // NULL screen variables
    uic_CalibrationScreen = NULL;
    ui_CalibrationScreen = NULL;
    ui_HomeButton2 = NULL;
    uic_CalibrationNextButton = NULL;
    ui_CalibrationNextButton = NULL;
    uic_CalibrationButtonNextText = NULL;
    ui_CalibrationButtonNextText = NULL;
    uic_CalibrateInstruction = NULL;
    ui_CalibrateInstruction = NULL;
    uic_GPS_Coordinate_Cal = NULL;
    ui_GPS_Coordinate_Cal = NULL;
    uic_CalibrationSetButton = NULL;
    ui_CalibrationSetButton = NULL;
    ui_CalibrationButtonNextText1 = NULL;

}
