// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CALIBRATIONSCREENADVANCED_H
#define UI_CALIBRATIONSCREENADVANCED_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalibrationScreenAdvanced
extern void ui_CalibrationScreenAdvanced_screen_init(void);
extern void ui_CalibrationScreenAdvanced_screen_destroy(void);
extern lv_obj_t * ui_CalibrationScreenAdvanced;
extern void ui_event_HomeButton1(lv_event_t * e);
extern lv_obj_t * ui_HomeButton1;
extern lv_obj_t * ui_CalibrationAdvHeader;
extern lv_obj_t * ui_CalibrationAdvGps;
extern lv_obj_t * ui_CalibrationAdvInstruction;
extern void ui_event_CalibrationPoint(lv_event_t * e);
extern lv_obj_t * ui_CalibrationPoint;
extern lv_obj_t * ui_CalibrationPointText;
extern void ui_event_RollerEW(lv_event_t * e);
extern lv_obj_t * ui_RollerEW;
extern void ui_event_RollerNS(lv_event_t * e);
extern lv_obj_t * ui_RollerNS;
extern lv_obj_t * ui_TriangleFrom;
extern lv_obj_t * ui_TriangleTo;
extern lv_obj_t * ui_CalFromRaw;
extern lv_obj_t * ui_CalToStored;
extern lv_obj_t * ui_SpinLock;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CalibrationScreenAdvanced;
extern lv_obj_t * uic_CalibrationAdvHeader;
extern lv_obj_t * uic_CalibrationAdvGps;
extern lv_obj_t * uic_CalibrationAdvInstruction;
extern lv_obj_t * uic_CalibrationPoint;
extern lv_obj_t * uic_CalibrationPointText;
extern lv_obj_t * uic_RollerEW;
extern lv_obj_t * uic_RollerNS;
extern lv_obj_t * uic_TriangleFrom;
extern lv_obj_t * uic_TriangleTo;
extern lv_obj_t * uic_CalFromRaw;
extern lv_obj_t * uic_CalToStored;
extern lv_obj_t * uic_SpinLock;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

