// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CALIBRATIONSCREEN_H
#define UI_CALIBRATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalibrationScreen
extern void ui_CalibrationScreen_screen_init(void);
extern void ui_CalibrationScreen_screen_destroy(void);
extern lv_obj_t * ui_CalibrationScreen;
extern void ui_event_HomeButton2(lv_event_t * e);
extern lv_obj_t * ui_HomeButton2;
extern lv_obj_t * ui_CalibrateFooter;
extern lv_obj_t * ui_CalibrationRawCoord;
extern lv_obj_t * ui_CalibrationInstruction;
extern void ui_event_CalibrationSetAsZero(lv_event_t * e);
extern lv_obj_t * ui_CalibrationSetAsZero;
extern lv_obj_t * ui_CalibrationSetAsZeroText;
extern void ui_event_CalibrationLatitudes(lv_event_t * e);
extern lv_obj_t * ui_CalibrationLatitudes;
extern lv_obj_t * ui_LatitudesText;
extern void ui_event_CalibrationLongitudes(lv_event_t * e);
extern lv_obj_t * ui_CalibrationLongitudes;
extern lv_obj_t * ui_LongitudesText;
extern void ui_event_CalibrationAdvanced(lv_event_t * e);
extern lv_obj_t * ui_CalibrationAdvanced;
extern lv_obj_t * ui_CalibrationAdvancedText;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CalibrationScreen;
extern lv_obj_t * uic_CalibrateFooter;
extern lv_obj_t * uic_CalibrationRawCoord;
extern lv_obj_t * uic_CalibrationInstruction;
extern lv_obj_t * uic_CalibrationSetAsZero;
extern lv_obj_t * uic_CalibrationSetAsZeroText;
extern lv_obj_t * uic_CalibrationLatitudes;
extern lv_obj_t * uic_LatitudesText;
extern lv_obj_t * uic_CalibrationLongitudes;
extern lv_obj_t * uic_CalibrationAdvanced;
extern lv_obj_t * uic_CalibrationAdvancedText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

