// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CALIBRATIONSCREEN_H
#define UI_CALIBRATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalibrationScreen
extern void ui_CalibrationScreen_screen_init(void);
extern void ui_CalibrationScreen_screen_destroy(void);
extern lv_obj_t * ui_CalibrationScreen;
extern void ui_event_HomeButton2(lv_event_t * e);
extern lv_obj_t * ui_HomeButton2;
extern void ui_event_CalibrationNextButton(lv_event_t * e);
extern lv_obj_t * ui_CalibrationNextButton;
extern lv_obj_t * ui_CalibrationButtonNextText;
extern lv_obj_t * ui_CalibrateInstruction;
extern lv_obj_t * ui_GPS_Coordinate_Cal;
extern void ui_event_CalibrationSetButton(lv_event_t * e);
extern lv_obj_t * ui_CalibrationSetButton;
extern lv_obj_t * ui_CalibrationButtonNextText1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CalibrationScreen;
extern lv_obj_t * uic_CalibrationNextButton;
extern lv_obj_t * uic_CalibrationButtonNextText;
extern lv_obj_t * uic_CalibrateInstruction;
extern lv_obj_t * uic_GPS_Coordinate_Cal;
extern lv_obj_t * uic_CalibrationSetButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

