// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_DatabaseProgress;
lv_obj_t * uic_DatabaseScreen;
lv_obj_t * ui_DatabaseScreen;
lv_obj_t * ui_HomeButton3;
lv_obj_t * ui_DatabaseProgress;

// event funtions
void ui_event_HomeButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_DatabaseScreen_screen_init(void)
{
    ui_DatabaseScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DatabaseScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton3 = lv_img_create(ui_DatabaseScreen);
    lv_img_set_src(ui_HomeButton3, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton3, 0);
    lv_obj_set_y(ui_HomeButton3, 168);
    lv_obj_set_align(ui_HomeButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_yellow);

    ui_DatabaseProgress = lv_label_create(ui_DatabaseScreen);
    lv_obj_set_width(ui_DatabaseProgress, 343);
    lv_obj_set_height(ui_DatabaseProgress, 283);
    lv_obj_set_x(ui_DatabaseProgress, 1);
    lv_obj_set_y(ui_DatabaseProgress, -10);
    lv_obj_set_align(ui_DatabaseProgress, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_DatabaseProgress, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_DatabaseProgress, "INSTRUCTION");
    lv_obj_set_style_text_align(ui_DatabaseProgress, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DatabaseProgress, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);
    uic_DatabaseScreen = ui_DatabaseScreen;
    uic_DatabaseProgress = ui_DatabaseProgress;

}

void ui_DatabaseScreen_screen_destroy(void)
{
    if(ui_DatabaseScreen) lv_obj_del(ui_DatabaseScreen);

    // NULL screen variables
    uic_DatabaseScreen = NULL;
    ui_DatabaseScreen = NULL;
    ui_HomeButton3 = NULL;
    uic_DatabaseProgress = NULL;
    ui_DatabaseProgress = NULL;

}
