// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_MapCursor;
lv_obj_t * uic_MapBanner;
lv_obj_t * uic_RebuildDatabaseButtonText;
lv_obj_t * uic_RebuildDatabase;
lv_obj_t * uic_WorldMap;
lv_obj_t * uic_DatabaseProgress1;
lv_obj_t * uic_DatabaseProgress;
lv_obj_t * uic_HomeButton3;
lv_obj_t * uic_DatabaseScreen;
lv_obj_t * ui_DatabaseScreen = NULL;
lv_obj_t * ui_HomeButton3 = NULL;
lv_obj_t * ui_DatabaseProgress = NULL;
lv_obj_t * ui_DatabaseProgress1 = NULL;
lv_obj_t * ui_WorldMap = NULL;
lv_obj_t * ui_RebuildDatabase = NULL;
lv_obj_t * ui_RebuildDatabaseButtonText = NULL;
lv_obj_t * ui_MapBanner = NULL;
lv_obj_t * ui_MapCursor = NULL;
// event funtions
void ui_event_HomeButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
        beep(e);
    }
}

void ui_event_RebuildDatabase(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        RebuildDatabase(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        RebuildDatabase(e);
    }
}

// build funtions

void ui_DatabaseScreen_screen_init(void)
{
    ui_DatabaseScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DatabaseScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton3 = lv_img_create(ui_DatabaseScreen);
    lv_img_set_src(ui_HomeButton3, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton3, 0);
    lv_obj_set_y(ui_HomeButton3, 195);
    lv_obj_set_align(ui_HomeButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_DatabaseProgress = lv_label_create(ui_DatabaseScreen);
    lv_obj_set_width(ui_DatabaseProgress, 343);
    lv_obj_set_height(ui_DatabaseProgress, 25);
    lv_obj_set_x(ui_DatabaseProgress, 1);
    lv_obj_set_y(ui_DatabaseProgress, -120);
    lv_obj_set_align(ui_DatabaseProgress, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_DatabaseProgress, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_DatabaseProgress, "PROGRESS");
    lv_obj_set_style_text_align(ui_DatabaseProgress, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DatabaseProgress, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DatabaseProgress1 = lv_label_create(ui_DatabaseScreen);
    lv_obj_set_width(ui_DatabaseProgress1, 343);
    lv_obj_set_height(ui_DatabaseProgress1, 25);
    lv_obj_set_x(ui_DatabaseProgress1, 0);
    lv_obj_set_y(ui_DatabaseProgress1, 116);
    lv_obj_set_align(ui_DatabaseProgress1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_DatabaseProgress1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_DatabaseProgress1, "FILE PROGRESS");
    lv_obj_set_style_text_align(ui_DatabaseProgress1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DatabaseProgress1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WorldMap = lv_img_create(ui_DatabaseScreen);
    lv_img_set_src(ui_WorldMap, &ui_img_stationsmap150k_png);
    lv_obj_set_width(ui_WorldMap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WorldMap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WorldMap, 1);
    lv_obj_set_y(ui_WorldMap, 0);
    lv_obj_set_align(ui_WorldMap, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WorldMap, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WorldMap, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_WorldMap, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WorldMap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WorldMap, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RebuildDatabase = lv_btn_create(ui_DatabaseScreen);
    lv_obj_set_width(ui_RebuildDatabase, 235);
    lv_obj_set_height(ui_RebuildDatabase, 50);
    lv_obj_set_x(ui_RebuildDatabase, 0);
    lv_obj_set_y(ui_RebuildDatabase, -170);
    lv_obj_set_align(ui_RebuildDatabase, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RebuildDatabase, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RebuildDatabase, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_RebuildDatabase, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_RebuildDatabase, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_RebuildDatabaseButtonText = lv_label_create(ui_DatabaseScreen);
    lv_obj_set_width(ui_RebuildDatabaseButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RebuildDatabaseButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RebuildDatabaseButtonText, 0);
    lv_obj_set_y(ui_RebuildDatabaseButtonText, -170);
    lv_obj_set_align(ui_RebuildDatabaseButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RebuildDatabaseButtonText, "REBUILD DATABASE");
    lv_obj_set_style_text_color(ui_RebuildDatabaseButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RebuildDatabaseButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RebuildDatabaseButtonText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RebuildDatabaseButtonText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapBanner = lv_label_create(ui_DatabaseScreen);
    lv_obj_set_width(ui_MapBanner, 240);
    lv_obj_set_height(ui_MapBanner, 146);
    lv_obj_set_align(ui_MapBanner, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_MapBanner, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_MapBanner, "All\nThose\nBeautiful\nInternet\nRadio\nStations\nAround\nThe\nWorld\n");
    ui_object_set_themeable_style_property(ui_MapBanner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_lightblue);
    ui_object_set_themeable_style_property(ui_MapBanner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_lightblue);
    lv_obj_set_style_text_align(ui_MapBanner, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MapBanner, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MapBanner, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_MapBanner, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_MapCursor = lv_img_create(ui_DatabaseScreen);
    lv_img_set_src(ui_MapCursor, &ui_img_circle16x16_png);
    lv_obj_set_width(ui_MapCursor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapCursor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MapCursor, -41);
    lv_obj_set_y(ui_MapCursor, 18);
    lv_obj_set_align(ui_MapCursor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MapCursor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MapCursor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_MapCursor, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_MapCursor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_MapCursor, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_opa(ui_MapCursor, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RebuildDatabase, ui_event_RebuildDatabase, LV_EVENT_ALL, NULL);
    uic_DatabaseScreen = ui_DatabaseScreen;
    uic_HomeButton3 = ui_HomeButton3;
    uic_DatabaseProgress = ui_DatabaseProgress;
    uic_DatabaseProgress1 = ui_DatabaseProgress1;
    uic_WorldMap = ui_WorldMap;
    uic_RebuildDatabase = ui_RebuildDatabase;
    uic_RebuildDatabaseButtonText = ui_RebuildDatabaseButtonText;
    uic_MapBanner = ui_MapBanner;
    uic_MapCursor = ui_MapCursor;

}

void ui_DatabaseScreen_screen_destroy(void)
{
    if(ui_DatabaseScreen) lv_obj_del(ui_DatabaseScreen);

    // NULL screen variables
    uic_DatabaseScreen = NULL;
    ui_DatabaseScreen = NULL;
    uic_HomeButton3 = NULL;
    ui_HomeButton3 = NULL;
    uic_DatabaseProgress = NULL;
    ui_DatabaseProgress = NULL;
    uic_DatabaseProgress1 = NULL;
    ui_DatabaseProgress1 = NULL;
    uic_WorldMap = NULL;
    ui_WorldMap = NULL;
    uic_RebuildDatabase = NULL;
    ui_RebuildDatabase = NULL;
    uic_RebuildDatabaseButtonText = NULL;
    ui_RebuildDatabaseButtonText = NULL;
    uic_MapBanner = NULL;
    ui_MapBanner = NULL;
    uic_MapCursor = NULL;
    ui_MapCursor = NULL;

}
