// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DATABASESCREEN_H
#define UI_DATABASESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DatabaseScreen
extern void ui_DatabaseScreen_screen_init(void);
extern void ui_DatabaseScreen_screen_destroy(void);
extern lv_obj_t * ui_DatabaseScreen;
extern void ui_event_HomeButton3(lv_event_t * e);
extern lv_obj_t * ui_HomeButton3;
extern lv_obj_t * ui_DatabaseProgress;
// CUSTOM VARIABLES
extern lv_obj_t * uic_DatabaseScreen;
extern lv_obj_t * uic_DatabaseProgress;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

