// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void CheckDatabase(lv_event_t * e);
void expertmode(lv_event_t * e);
void CalibrationNextButton(lv_event_t * e);
void CalibrationSetButton(lv_event_t * e);
void click1(lv_event_t * e);
void click2(lv_event_t * e);
void click3(lv_event_t * e);
void click4(lv_event_t * e);
void click5(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
