// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void RadioGlobeClick(lv_event_t * e);
void beep(lv_event_t * e);
void SetupEnter(lv_event_t * e);
void CalibrationEnter(lv_event_t * e);
void DatabaseEnter(lv_event_t * e);
void ResetAllEnter(lv_event_t * e);
void CalibrationSetAsZero(lv_event_t * e);
void CalibrationLattitudes(lv_event_t * e);
void CalibrationLongitudes(lv_event_t * e);
void CalibrationAdvanced(lv_event_t * e);
void RebuildDatabase(lv_event_t * e);
void click1(lv_event_t * e);
void click2(lv_event_t * e);
void click3(lv_event_t * e);
void click4(lv_event_t * e);
void click5(lv_event_t * e);
void StationRollPressed(lv_event_t * e);
void StationRollVal(lv_event_t * e);
void StationRollClicked(lv_event_t * e);
void station1(lv_event_t * e);
void station2(lv_event_t * e);
void station3(lv_event_t * e);
void station4(lv_event_t * e);
void CalibratePoint(lv_event_t * e);
void RollerNSorEWChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
