// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_arrowright;
lv_obj_t * uic_arrowleft;
lv_obj_t * uic_Power_Off_Icon;
lv_obj_t * uic_Station_Name;
lv_obj_t * uic_Time_Zone;
lv_obj_t * uic_BatteryVoltage;
lv_obj_t * uic_Battery_Icon_High;
lv_obj_t * uic_Battery_Icon_Medium;
lv_obj_t * uic_Battery_Icon_Low;
lv_obj_t * uic_SettingButton;
lv_obj_t * uic_Local_Time;
lv_obj_t * uic_Station_Title;
lv_obj_t * uic_HomeGps;
lv_obj_t * uic_VolumeValue;
lv_obj_t * uic_VolumeArc;
lv_obj_t * uic_Home;
lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_VolumeArc = NULL;
lv_obj_t * ui_Text_Volume = NULL;
lv_obj_t * ui_VolumeValue = NULL;
lv_obj_t * ui_Text_Radio_Globe = NULL;
lv_obj_t * ui_Text_Now_Playing = NULL;
lv_obj_t * ui_HomeGps = NULL;
lv_obj_t * ui_Station_Title = NULL;
lv_obj_t * ui_Local_Time = NULL;
lv_obj_t * ui_SettingButton = NULL;
lv_obj_t * ui_Battery_Icon_Low = NULL;
lv_obj_t * ui_Battery_Icon_Medium = NULL;
lv_obj_t * ui_Battery_Icon_High = NULL;
lv_obj_t * ui_BatteryVoltage = NULL;
lv_obj_t * ui_Time_Zone = NULL;
lv_obj_t * ui_Station_Name = NULL;
lv_obj_t * ui_Power_Off_Icon = NULL;
lv_obj_t * ui_arrowleft = NULL;
lv_obj_t * ui_arrowright = NULL;
// event funtions
void ui_event_VolumeArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_VolumeValue, target, "", "");
    }
}

void ui_event_Text_Radio_Globe(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        RadioGlobeClick(e);
        beep(e);
    }
}

void ui_event_Text_Now_Playing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StationInfo(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        StationInfo(e);
    }
}

void ui_event_SettingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        beep(e);
        SetupEnter(e);
    }
}

void ui_event_Power_Off_Icon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PowerCycle(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        PowerCycle(e);
    }
}

void ui_event_arrowleft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ToneControlScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ToneControlScreen_screen_init);
    }
}

void ui_event_arrowright(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Favorites, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Favorites_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Home, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Home, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeArc = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_VolumeArc, 220);
    lv_obj_set_height(ui_VolumeArc, 220);
    lv_obj_set_x(ui_VolumeArc, 0);
    lv_obj_set_y(ui_VolumeArc, 114);
    lv_obj_set_align(ui_VolumeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_VolumeArc, 0);

    lv_obj_set_style_arc_color(ui_VolumeArc, lv_color_hex(0xFBFF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_VolumeArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolumeArc, lv_color_hex(0xF1FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Text_Volume = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Text_Volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Volume, 0);
    lv_obj_set_y(ui_Text_Volume, 196);
    lv_obj_set_align(ui_Text_Volume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Volume, "VOLUME");
    lv_obj_set_style_text_color(ui_Text_Volume, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text_Volume, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeValue = lv_label_create(ui_Home);
    lv_obj_set_width(ui_VolumeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolumeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolumeValue, 0);
    lv_obj_set_y(ui_VolumeValue, 108);
    lv_obj_set_align(ui_VolumeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumeValue, "0");
    lv_obj_set_style_text_color(ui_VolumeValue, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumeValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_VolumeValue, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Text_Radio_Globe = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Text_Radio_Globe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Radio_Globe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Radio_Globe, 0);
    lv_obj_set_y(ui_Text_Radio_Globe, -118);
    lv_obj_set_align(ui_Text_Radio_Globe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Radio_Globe, "RADIO GLOBE");
    lv_obj_add_flag(ui_Text_Radio_Globe, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Text_Radio_Globe, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Text_Radio_Globe, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Radio_Globe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Text_Radio_Globe, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text_Radio_Globe, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text_Now_Playing = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Text_Now_Playing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Now_Playing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Now_Playing, 0);
    lv_obj_set_y(ui_Text_Now_Playing, -50);
    lv_obj_set_align(ui_Text_Now_Playing, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Now_Playing, "NOW PLAYING");
    lv_obj_add_flag(ui_Text_Now_Playing, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Text_Now_Playing, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Now_Playing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Text_Now_Playing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeGps = lv_label_create(ui_Home);
    lv_obj_set_width(ui_HomeGps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeGps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeGps, 0);
    lv_obj_set_y(ui_HomeGps, -213);
    lv_obj_set_align(ui_HomeGps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeGps, "N00.0  -  W00.0");
    lv_obj_clear_flag(ui_HomeGps, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_HomeGps, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_HomeGps, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_turquoise);
    lv_obj_set_style_text_align(ui_HomeGps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeGps, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Station_Title = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Station_Title, 360);
    lv_obj_set_height(ui_Station_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Station_Title, 0);
    lv_obj_set_y(ui_Station_Title, -28);
    lv_obj_set_align(ui_Station_Title, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Station_Title, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Station_Title, "");
    lv_obj_clear_flag(ui_Station_Title, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_style_text_color(ui_Station_Title, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Station_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Station_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Station_Title, &ui_font_font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Local_Time = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Local_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Local_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Local_Time, 0);
    lv_obj_set_y(ui_Local_Time, -189);
    lv_obj_set_align(ui_Local_Time, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Local_Time, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Local_Time, "STATION TIME  19:21");
    ui_object_set_themeable_style_property(ui_Local_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_Local_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_turquoise);
    lv_obj_set_style_text_align(ui_Local_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Local_Time, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingButton = lv_img_create(ui_Home);
    lv_img_set_src(ui_SettingButton, &ui_img_cog_png);
    lv_obj_set_width(ui_SettingButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingButton, -156);
    lv_obj_set_y(ui_SettingButton, 70);
    lv_obj_set_align(ui_SettingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_SettingButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_Battery_Icon_Low = lv_img_create(ui_Home);
    lv_img_set_src(ui_Battery_Icon_Low, &ui_img_batterylow_png);
    lv_obj_set_width(ui_Battery_Icon_Low, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Icon_Low, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Icon_Low, 162);
    lv_obj_set_y(ui_Battery_Icon_Low, 70);
    lv_obj_set_align(ui_Battery_Icon_Low, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Battery_Icon_Low, LV_STATE_USER_1 | LV_STATE_USER_2 | LV_STATE_USER_3);       /// States
    lv_obj_add_flag(ui_Battery_Icon_Low, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery_Icon_Low, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Battery_Icon_Low, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_Battery_Icon_Low, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_Battery_Icon_Medium = lv_img_create(ui_Home);
    lv_img_set_src(ui_Battery_Icon_Medium, &ui_img_batterymedium_png);
    lv_obj_set_width(ui_Battery_Icon_Medium, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Icon_Medium, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Icon_Medium, 162);
    lv_obj_set_y(ui_Battery_Icon_Medium, 70);
    lv_obj_set_align(ui_Battery_Icon_Medium, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Battery_Icon_Medium, LV_STATE_USER_1 | LV_STATE_USER_2 | LV_STATE_USER_3);       /// States
    lv_obj_add_flag(ui_Battery_Icon_Medium, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery_Icon_Medium, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Battery_Icon_Medium, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_Battery_Icon_Medium, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_turquoise);

    ui_Battery_Icon_High = lv_img_create(ui_Home);
    lv_img_set_src(ui_Battery_Icon_High, &ui_img_batteryhigh_png);
    lv_obj_set_width(ui_Battery_Icon_High, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Icon_High, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Icon_High, 162);
    lv_obj_set_y(ui_Battery_Icon_High, 70);
    lv_obj_set_align(ui_Battery_Icon_High, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Battery_Icon_High, LV_STATE_USER_1 | LV_STATE_USER_2 | LV_STATE_USER_3);       /// States
    lv_obj_add_flag(ui_Battery_Icon_High, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery_Icon_High, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Battery_Icon_High, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_Battery_Icon_High, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_BatteryVoltage = lv_label_create(ui_Home);
    lv_obj_set_height(ui_BatteryVoltage, 18);
    lv_obj_set_width(ui_BatteryVoltage, LV_SIZE_CONTENT);   /// 52
    lv_obj_set_x(ui_BatteryVoltage, 162);
    lv_obj_set_y(ui_BatteryVoltage, 121);
    lv_obj_set_align(ui_BatteryVoltage, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_BatteryVoltage, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_BatteryVoltage, "3.51V");
    lv_obj_clear_flag(ui_BatteryVoltage,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_BatteryVoltage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_Zone = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Time_Zone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Zone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Zone, 0);
    lv_obj_set_y(ui_Time_Zone, -166);
    lv_obj_set_align(ui_Time_Zone, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Time_Zone, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Time_Zone, "TIME ZONE");
    ui_object_set_themeable_style_property(ui_Time_Zone, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_Time_Zone, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_turquoise);
    lv_obj_set_style_text_align(ui_Time_Zone, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_Zone, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Station_Name = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Station_Name, 360);
    lv_obj_set_height(ui_Station_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Station_Name, 0);
    lv_obj_set_y(ui_Station_Name, -75);
    lv_obj_set_align(ui_Station_Name, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Station_Name, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Station_Name, "STATION NAME");
    lv_obj_set_style_text_color(ui_Station_Name, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Station_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Station_Name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Station_Name, &ui_font_font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Power_Off_Icon = lv_img_create(ui_Home);
    lv_img_set_src(ui_Power_Off_Icon, &ui_img_power75x75_png);
    lv_obj_set_width(ui_Power_Off_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Power_Off_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Power_Off_Icon, 0);
    lv_obj_set_y(ui_Power_Off_Icon, 108);
    lv_obj_set_align(ui_Power_Off_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Power_Off_Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Power_Off_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Power_Off_Icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_green);
    ui_object_set_themeable_style_property(ui_Power_Off_Icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_green);

    ui_arrowleft = lv_img_create(ui_Home);
    lv_img_set_src(ui_arrowleft, &ui_img_arrow_left_bold_32x32_png);
    lv_obj_set_width(ui_arrowleft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arrowleft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_arrowleft, -220);
    lv_obj_set_y(ui_arrowleft, 0);
    lv_obj_set_align(ui_arrowleft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrowleft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arrowleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_arrowleft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_arrowleft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_arrowright = lv_img_create(ui_Home);
    lv_img_set_src(ui_arrowright, &ui_img_arrow_right_bold_32x32_png);
    lv_obj_set_width(ui_arrowright, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arrowright, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_arrowright, 210);
    lv_obj_set_y(ui_arrowright, 0);
    lv_obj_set_align(ui_arrowright, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrowright, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arrowright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_arrowright, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_arrowright, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    lv_obj_add_event_cb(ui_VolumeArc, ui_event_VolumeArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Text_Radio_Globe, ui_event_Text_Radio_Globe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Text_Now_Playing, ui_event_Text_Now_Playing, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingButton, ui_event_SettingButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Power_Off_Icon, ui_event_Power_Off_Icon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arrowleft, ui_event_arrowleft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arrowright, ui_event_arrowright, LV_EVENT_ALL, NULL);
    uic_Home = ui_Home;
    uic_VolumeArc = ui_VolumeArc;
    uic_VolumeValue = ui_VolumeValue;
    uic_HomeGps = ui_HomeGps;
    uic_Station_Title = ui_Station_Title;
    uic_Local_Time = ui_Local_Time;
    uic_SettingButton = ui_SettingButton;
    uic_Battery_Icon_Low = ui_Battery_Icon_Low;
    uic_Battery_Icon_Medium = ui_Battery_Icon_Medium;
    uic_Battery_Icon_High = ui_Battery_Icon_High;
    uic_BatteryVoltage = ui_BatteryVoltage;
    uic_Time_Zone = ui_Time_Zone;
    uic_Station_Name = ui_Station_Name;
    uic_Power_Off_Icon = ui_Power_Off_Icon;
    uic_arrowleft = ui_arrowleft;
    uic_arrowright = ui_arrowright;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_Home = NULL;
    ui_Home = NULL;
    uic_VolumeArc = NULL;
    ui_VolumeArc = NULL;
    ui_Text_Volume = NULL;
    uic_VolumeValue = NULL;
    ui_VolumeValue = NULL;
    ui_Text_Radio_Globe = NULL;
    ui_Text_Now_Playing = NULL;
    uic_HomeGps = NULL;
    ui_HomeGps = NULL;
    uic_Station_Title = NULL;
    ui_Station_Title = NULL;
    uic_Local_Time = NULL;
    ui_Local_Time = NULL;
    uic_SettingButton = NULL;
    ui_SettingButton = NULL;
    uic_Battery_Icon_Low = NULL;
    ui_Battery_Icon_Low = NULL;
    uic_Battery_Icon_Medium = NULL;
    ui_Battery_Icon_Medium = NULL;
    uic_Battery_Icon_High = NULL;
    ui_Battery_Icon_High = NULL;
    uic_BatteryVoltage = NULL;
    ui_BatteryVoltage = NULL;
    uic_Time_Zone = NULL;
    ui_Time_Zone = NULL;
    uic_Station_Name = NULL;
    ui_Station_Name = NULL;
    uic_Power_Off_Icon = NULL;
    ui_Power_Off_Icon = NULL;
    uic_arrowleft = NULL;
    ui_arrowleft = NULL;
    uic_arrowright = NULL;
    ui_arrowright = NULL;

}
