// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Station_Name;
lv_obj_t * uic_Time_Zone;
lv_obj_t * uic_BatteryVoltage;
lv_obj_t * uic_Battery_Icon;
lv_obj_t * uic_SettingButton;
lv_obj_t * uic_Local_Time;
lv_obj_t * uic_Station_Title;
lv_obj_t * uic_GPS_Coordinate;
lv_obj_t * uic_VolumeValue;
lv_obj_t * uic_VolumeArc;
lv_obj_t * uic_Home;
lv_obj_t * ui_Home;
lv_obj_t * ui_VolumeArc;
lv_obj_t * ui_Text_Volume;
lv_obj_t * ui_VolumeValue;
lv_obj_t * ui_Text_Radio_Globe;
lv_obj_t * ui_Text_Now_Playing;
lv_obj_t * ui_GPS_Coordinate;
lv_obj_t * ui_Station_Title;
lv_obj_t * ui_Local_Time;
lv_obj_t * ui_SettingButton;
lv_obj_t * ui_Battery_Icon;
lv_obj_t * ui_BatteryVoltage;
lv_obj_t * ui_Time_Zone;
lv_obj_t * ui_Station_Name;

// event funtions
void ui_event_VolumeArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_VolumeValue, target, "", "");
    }
}

void ui_event_SettingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetupScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SetupScreen_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Home, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_img_src(ui_Home, &ui_img_volume_off_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_VolumeArc = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_VolumeArc, 220);
    lv_obj_set_height(ui_VolumeArc, 220);
    lv_obj_set_x(ui_VolumeArc, 0);
    lv_obj_set_y(ui_VolumeArc, 114);
    lv_obj_set_align(ui_VolumeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_VolumeArc, 50);

    lv_obj_set_style_arc_color(ui_VolumeArc, lv_color_hex(0xFBFF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_VolumeArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolumeArc, lv_color_hex(0xF1FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Text_Volume = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Text_Volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Volume, 0);
    lv_obj_set_y(ui_Text_Volume, 196);
    lv_obj_set_align(ui_Text_Volume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Volume, "VOLUME");
    lv_obj_set_style_text_color(ui_Text_Volume, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text_Volume, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeValue = lv_label_create(ui_Home);
    lv_obj_set_width(ui_VolumeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolumeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolumeValue, 0);
    lv_obj_set_y(ui_VolumeValue, 108);
    lv_obj_set_align(ui_VolumeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumeValue, "50");
    lv_obj_set_style_text_color(ui_VolumeValue, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumeValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text_Radio_Globe = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Text_Radio_Globe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Radio_Globe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Radio_Globe, 0);
    lv_obj_set_y(ui_Text_Radio_Globe, -118);
    lv_obj_set_align(ui_Text_Radio_Globe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Radio_Globe, "RADIO GLOBE");
    lv_obj_set_style_text_color(ui_Text_Radio_Globe, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Radio_Globe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Text_Radio_Globe, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text_Radio_Globe, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text_Now_Playing = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Text_Now_Playing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Now_Playing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Now_Playing, 0);
    lv_obj_set_y(ui_Text_Now_Playing, -45);
    lv_obj_set_align(ui_Text_Now_Playing, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Now_Playing, "NOW PLAYING");
    lv_obj_set_style_text_color(ui_Text_Now_Playing, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Now_Playing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Text_Now_Playing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Coordinate = lv_label_create(ui_Home);
    lv_obj_set_width(ui_GPS_Coordinate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Coordinate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Coordinate, 0);
    lv_obj_set_y(ui_GPS_Coordinate, -213);
    lv_obj_set_align(ui_GPS_Coordinate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPS_Coordinate, "N00.0  -  W00.0");
    lv_obj_clear_flag(ui_GPS_Coordinate,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_GPS_Coordinate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_GPS_Coordinate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellow);
    lv_obj_set_style_text_align(ui_GPS_Coordinate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPS_Coordinate, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Station_Title = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Station_Title, 341);
    lv_obj_set_height(ui_Station_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Station_Title, 0);
    lv_obj_set_y(ui_Station_Title, -21);
    lv_obj_set_align(ui_Station_Title, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Station_Title, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Station_Title, "RADIO AMSTERDAM JAZZ");
    lv_obj_clear_flag(ui_Station_Title, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_style_text_color(ui_Station_Title, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Station_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Station_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Station_Title, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Local_Time = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Local_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Local_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Local_Time, 0);
    lv_obj_set_y(ui_Local_Time, -189);
    lv_obj_set_align(ui_Local_Time, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Local_Time, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Local_Time, "STATION TIME  19:21");
    ui_object_set_themeable_style_property(ui_Local_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_Local_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellow);
    lv_obj_set_style_text_align(ui_Local_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Local_Time, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingButton = lv_img_create(ui_Home);
    lv_img_set_src(ui_SettingButton, &ui_img_cog_png);
    lv_obj_set_width(ui_SettingButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingButton, -156);
    lv_obj_set_y(ui_SettingButton, 70);
    lv_obj_set_align(ui_SettingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_SettingButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_yellow);

    ui_Battery_Icon = lv_img_create(ui_Home);
    lv_img_set_src(ui_Battery_Icon, &ui_img_battery_medium_png);
    lv_obj_set_width(ui_Battery_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Icon, 162);
    lv_obj_set_y(ui_Battery_Icon, 70);
    lv_obj_set_align(ui_Battery_Icon, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Battery_Icon, LV_STATE_USER_1 | LV_STATE_USER_2 | LV_STATE_USER_3);       /// States
    lv_obj_add_flag(ui_Battery_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Battery_Icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_Battery_Icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_yellow);

    ui_BatteryVoltage = lv_label_create(ui_Home);
    lv_obj_set_height(ui_BatteryVoltage, 18);
    lv_obj_set_width(ui_BatteryVoltage, LV_SIZE_CONTENT);   /// 52
    lv_obj_set_x(ui_BatteryVoltage, 162);
    lv_obj_set_y(ui_BatteryVoltage, 121);
    lv_obj_set_align(ui_BatteryVoltage, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_BatteryVoltage, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_BatteryVoltage, " 5.0V ");
    lv_obj_clear_flag(ui_BatteryVoltage,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Time_Zone = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Time_Zone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Zone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Zone, 0);
    lv_obj_set_y(ui_Time_Zone, -166);
    lv_obj_set_align(ui_Time_Zone, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Time_Zone, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Time_Zone, "TIME ZONE");
    ui_object_set_themeable_style_property(ui_Time_Zone, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_Time_Zone, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellow);
    lv_obj_set_style_text_align(ui_Time_Zone, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_Zone, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Station_Name = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Station_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Station_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Station_Name, 0);
    lv_obj_set_y(ui_Station_Name, -71);
    lv_obj_set_align(ui_Station_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Station_Name, "STATION NAME");
    lv_obj_set_style_text_color(ui_Station_Name, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Station_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Station_Name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Station_Name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_VolumeArc, ui_event_VolumeArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingButton, ui_event_SettingButton, LV_EVENT_ALL, NULL);
    uic_Home = ui_Home;
    uic_VolumeArc = ui_VolumeArc;
    uic_VolumeValue = ui_VolumeValue;
    uic_GPS_Coordinate = ui_GPS_Coordinate;
    uic_Station_Title = ui_Station_Title;
    uic_Local_Time = ui_Local_Time;
    uic_SettingButton = ui_SettingButton;
    uic_Battery_Icon = ui_Battery_Icon;
    uic_BatteryVoltage = ui_BatteryVoltage;
    uic_Time_Zone = ui_Time_Zone;
    uic_Station_Name = ui_Station_Name;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_Home = NULL;
    ui_Home = NULL;
    uic_VolumeArc = NULL;
    ui_VolumeArc = NULL;
    ui_Text_Volume = NULL;
    uic_VolumeValue = NULL;
    ui_VolumeValue = NULL;
    ui_Text_Radio_Globe = NULL;
    ui_Text_Now_Playing = NULL;
    uic_GPS_Coordinate = NULL;
    ui_GPS_Coordinate = NULL;
    uic_Station_Title = NULL;
    ui_Station_Title = NULL;
    uic_Local_Time = NULL;
    ui_Local_Time = NULL;
    uic_SettingButton = NULL;
    ui_SettingButton = NULL;
    uic_Battery_Icon = NULL;
    ui_Battery_Icon = NULL;
    uic_BatteryVoltage = NULL;
    ui_BatteryVoltage = NULL;
    uic_Time_Zone = NULL;
    ui_Time_Zone = NULL;
    uic_Station_Name = NULL;
    ui_Station_Name = NULL;

}
