// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern void ui_event_VolumeArc(lv_event_t * e);
extern lv_obj_t * ui_VolumeArc;
extern lv_obj_t * ui_Text_Volume;
extern lv_obj_t * ui_VolumeValue;
extern void ui_event_Text_Radio_Globe(lv_event_t * e);
extern lv_obj_t * ui_Text_Radio_Globe;
extern void ui_event_Text_Now_Playing(lv_event_t * e);
extern lv_obj_t * ui_Text_Now_Playing;
extern lv_obj_t * ui_HomeGps;
extern lv_obj_t * ui_Station_Title;
extern lv_obj_t * ui_Local_Time;
extern void ui_event_SettingButton(lv_event_t * e);
extern lv_obj_t * ui_SettingButton;
extern lv_obj_t * ui_Battery_Icon_Low;
extern lv_obj_t * ui_Battery_Icon_Medium;
extern lv_obj_t * ui_Battery_Icon_High;
extern lv_obj_t * ui_BatteryVoltage;
extern lv_obj_t * ui_Time_Zone;
extern lv_obj_t * ui_Station_Name;
extern void ui_event_Power_Off_Icon(lv_event_t * e);
extern lv_obj_t * ui_Power_Off_Icon;
extern void ui_event_arrowleft(lv_event_t * e);
extern lv_obj_t * ui_arrowleft;
extern void ui_event_arrowright(lv_event_t * e);
extern lv_obj_t * ui_arrowright;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Home;
extern lv_obj_t * uic_VolumeArc;
extern lv_obj_t * uic_VolumeValue;
extern lv_obj_t * uic_HomeGps;
extern lv_obj_t * uic_Station_Title;
extern lv_obj_t * uic_Local_Time;
extern lv_obj_t * uic_SettingButton;
extern lv_obj_t * uic_Battery_Icon_Low;
extern lv_obj_t * uic_Battery_Icon_Medium;
extern lv_obj_t * uic_Battery_Icon_High;
extern lv_obj_t * uic_BatteryVoltage;
extern lv_obj_t * uic_Time_Zone;
extern lv_obj_t * uic_Station_Name;
extern lv_obj_t * uic_Power_Off_Icon;
extern lv_obj_t * uic_arrowleft;
extern lv_obj_t * uic_arrowright;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

