// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ICONSTORAGE_H
#define UI_ICONSTORAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_IconStorage
extern void ui_IconStorage_screen_init(void);
extern void ui_IconStorage_screen_destroy(void);
extern lv_obj_t * ui_IconStorage;
extern lv_obj_t * ui_BatterIconLow;
extern lv_obj_t * ui_BatteryIconHigh;
// CUSTOM VARIABLES
extern lv_obj_t * uic_IconStorage;
extern lv_obj_t * uic_BatterIconLow;
extern lv_obj_t * uic_BatteryIconHigh;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

