// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_pass1;
lv_obj_t * uic_PasswordScreen;
lv_obj_t * ui_PasswordScreen;
lv_obj_t * ui_pass1;
lv_obj_t * ui_pass2;
lv_obj_t * ui_pass3;
lv_obj_t * ui_pass4;
lv_obj_t * ui_pass5;
lv_obj_t * ui_Title;
lv_obj_t * ui_HomeButton4;
lv_obj_t * ui_CharG;
lv_obj_t * ui_CharL;
lv_obj_t * ui_CharO;
lv_obj_t * ui_CharB;
lv_obj_t * ui_CharE;
lv_obj_t * ui_Title1;
lv_obj_t * ui_lockstatus;

// event funtions
void ui_event_pass1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        click1(e);
    }
}

void ui_event_pass2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        click2(e);
        (e);
    }
}

void ui_event_pass3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        click3(e);
        (e);
    }
}

void ui_event_pass4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        click4(e);
        (e);
    }
}

void ui_event_pass5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        click5(e);
        (e);
    }
}

void ui_event_HomeButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_PasswordScreen_screen_init(void)
{
    ui_PasswordScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PasswordScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pass1 = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_pass1, 75);
    lv_obj_set_height(ui_pass1, 75);
    lv_obj_set_x(ui_pass1, -180);
    lv_obj_set_y(ui_pass1, 0);
    lv_obj_set_align(ui_pass1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pass1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pass1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pass1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_pass1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_pass2 = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_pass2, 75);
    lv_obj_set_height(ui_pass2, 75);
    lv_obj_set_x(ui_pass2, -90);
    lv_obj_set_y(ui_pass2, 0);
    lv_obj_set_align(ui_pass2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pass2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pass2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pass2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_pass2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_pass3 = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_pass3, 75);
    lv_obj_set_height(ui_pass3, 75);
    lv_obj_set_align(ui_pass3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pass3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pass3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pass3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_pass3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_pass4 = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_pass4, 75);
    lv_obj_set_height(ui_pass4, 75);
    lv_obj_set_x(ui_pass4, 90);
    lv_obj_set_y(ui_pass4, 0);
    lv_obj_set_align(ui_pass4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pass4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pass4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pass4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_pass4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_pass5 = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_pass5, 75);
    lv_obj_set_height(ui_pass5, 75);
    lv_obj_set_x(ui_pass5, 180);
    lv_obj_set_y(ui_pass5, 0);
    lv_obj_set_align(ui_pass5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pass5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pass5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pass5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_pass5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_Title = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title, 0);
    lv_obj_set_y(ui_Title, -141);
    lv_obj_set_align(ui_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title, "SECRET CODE TO UNLOCK");
    lv_obj_set_style_text_align(ui_Title, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton4 = lv_img_create(ui_PasswordScreen);
    lv_img_set_src(ui_HomeButton4, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton4, 0);
    lv_obj_set_y(ui_HomeButton4, 168);
    lv_obj_set_align(ui_HomeButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_HomeButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_yellow);

    ui_CharG = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_CharG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharG, 90);
    lv_obj_set_y(ui_CharG, 0);
    lv_obj_set_align(ui_CharG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharG, "G");
    lv_obj_set_style_text_color(ui_CharG, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CharG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CharG, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharG, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharL = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_CharL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharL, -90);
    lv_obj_set_y(ui_CharL, 0);
    lv_obj_set_align(ui_CharL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharL, "L");
    lv_obj_set_style_text_color(ui_CharL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CharL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CharL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharL, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharO = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_CharO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharO, -180);
    lv_obj_set_y(ui_CharO, 0);
    lv_obj_set_align(ui_CharO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharO, "O");
    lv_obj_set_style_text_color(ui_CharO, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CharO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CharO, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharO, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharB = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_CharB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharB, 180);
    lv_obj_set_y(ui_CharB, 0);
    lv_obj_set_align(ui_CharB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharB, "B");
    lv_obj_set_style_text_color(ui_CharB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CharB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CharB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharB, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharE = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_CharE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CharE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharE, "E");
    lv_obj_set_style_text_color(ui_CharE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CharE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CharE, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharE, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title1 = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_Title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title1, 1);
    lv_obj_set_y(ui_Title1, -102);
    lv_obj_set_align(ui_Title1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title1, "");
    lv_obj_set_style_text_align(ui_Title1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lockstatus = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_lockstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lockstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lockstatus, 0);
    lv_obj_set_y(ui_lockstatus, -90);
    lv_obj_set_align(ui_lockstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lockstatus, "LOCKED");
    lv_obj_set_style_text_color(ui_lockstatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lockstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lockstatus, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lockstatus, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_pass1, ui_event_pass1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pass2, ui_event_pass2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pass3, ui_event_pass3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pass4, ui_event_pass4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pass5, ui_event_pass5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton4, ui_event_HomeButton4, LV_EVENT_ALL, NULL);
    uic_PasswordScreen = ui_PasswordScreen;
    uic_pass1 = ui_pass1;

}

void ui_PasswordScreen_screen_destroy(void)
{
    if(ui_PasswordScreen) lv_obj_del(ui_PasswordScreen);

    // NULL screen variables
    uic_PasswordScreen = NULL;
    ui_PasswordScreen = NULL;
    uic_pass1 = NULL;
    ui_pass1 = NULL;
    ui_pass2 = NULL;
    ui_pass3 = NULL;
    ui_pass4 = NULL;
    ui_pass5 = NULL;
    ui_Title = NULL;
    ui_HomeButton4 = NULL;
    ui_CharG = NULL;
    ui_CharL = NULL;
    ui_CharO = NULL;
    ui_CharB = NULL;
    ui_CharE = NULL;
    ui_Title1 = NULL;
    ui_lockstatus = NULL;

}
