// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_POWER_H
#define UI_POWER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Power
extern void ui_Power_screen_init(void);
extern void ui_Power_screen_destroy(void);
extern lv_obj_t * ui_Power;
extern void ui_event_Big_Power_Off_Icon(lv_event_t * e);
extern lv_obj_t * ui_Big_Power_Off_Icon;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Power;
extern lv_obj_t * uic_Big_Power_Off_Icon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

