// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STATIONSELECTSCREEN_H
#define UI_STATIONSELECTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StationSelectScreen
extern void ui_StationSelectScreen_screen_init(void);
extern void ui_StationSelectScreen_screen_destroy(void);
extern lv_obj_t * ui_StationSelectScreen;
extern void ui_event_StationRoller(lv_event_t * e);
extern lv_obj_t * ui_StationRoller;
extern void ui_event_HomeButton5(lv_event_t * e);
extern lv_obj_t * ui_HomeButton5;
extern lv_obj_t * ui_StationRollerHeader;
extern lv_obj_t * ui_StationRollerComment;
extern lv_obj_t * ui_StationRollerSelected;
// CUSTOM VARIABLES
extern lv_obj_t * uic_StationSelectScreen;
extern lv_obj_t * uic_StationRoller;
extern lv_obj_t * uic_StationRollerSelected;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

