// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_DatabaseButtonText;
lv_obj_t * uic_DatabaseButton;
lv_obj_t * uic_CalibrationButtonText;
lv_obj_t * uic_CalibrationButton;
lv_obj_t * uic_HomeButton;
lv_obj_t * uic_SetupScreen;
lv_obj_t * ui_SetupScreen;
lv_obj_t * ui_HomeButton;
lv_obj_t * ui_CalibrationButton;
lv_obj_t * ui_CalibrationButtonText;
lv_obj_t * ui_DatabaseButton;
lv_obj_t * ui_DatabaseButtonText;

// event funtions
void ui_event_HomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_CalibrationButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalibrationScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_CalibrationScreen_screen_init);
    }
}

void ui_event_DatabaseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CheckDatabase(e);
    }
}

// build funtions

void ui_SetupScreen_screen_init(void)
{
    ui_SetupScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetupScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton = lv_img_create(ui_SetupScreen);
    lv_img_set_src(ui_HomeButton, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton, 0);
    lv_obj_set_y(ui_HomeButton, 168);
    lv_obj_set_align(ui_HomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_HomeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_yellow);

    ui_CalibrationButton = lv_btn_create(ui_SetupScreen);
    lv_obj_set_width(ui_CalibrationButton, 200);
    lv_obj_set_height(ui_CalibrationButton, 50);
    lv_obj_set_x(ui_CalibrationButton, 0);
    lv_obj_set_y(ui_CalibrationButton, -118);
    lv_obj_set_align(ui_CalibrationButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_CalibrationButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_CalibrationButtonText = lv_label_create(ui_SetupScreen);
    lv_obj_set_width(ui_CalibrationButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationButtonText, 0);
    lv_obj_set_y(ui_CalibrationButtonText, -117);
    lv_obj_set_align(ui_CalibrationButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationButtonText, "CALIBRATION");
    lv_obj_set_style_text_color(ui_CalibrationButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationButtonText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DatabaseButton = lv_btn_create(ui_SetupScreen);
    lv_obj_set_width(ui_DatabaseButton, 200);
    lv_obj_set_height(ui_DatabaseButton, 50);
    lv_obj_set_x(ui_DatabaseButton, 0);
    lv_obj_set_y(ui_DatabaseButton, -46);
    lv_obj_set_align(ui_DatabaseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DatabaseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DatabaseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DatabaseButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_DatabaseButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellow);

    ui_DatabaseButtonText = lv_label_create(ui_SetupScreen);
    lv_obj_set_width(ui_DatabaseButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DatabaseButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DatabaseButtonText, 2);
    lv_obj_set_y(ui_DatabaseButtonText, -47);
    lv_obj_set_align(ui_DatabaseButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DatabaseButtonText, "DATABASE");
    lv_obj_set_style_text_color(ui_DatabaseButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DatabaseButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DatabaseButtonText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationButton, ui_event_CalibrationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DatabaseButton, ui_event_DatabaseButton, LV_EVENT_ALL, NULL);
    uic_SetupScreen = ui_SetupScreen;
    uic_HomeButton = ui_HomeButton;
    uic_CalibrationButton = ui_CalibrationButton;
    uic_CalibrationButtonText = ui_CalibrationButtonText;
    uic_DatabaseButton = ui_DatabaseButton;
    uic_DatabaseButtonText = ui_DatabaseButtonText;

}

void ui_SetupScreen_screen_destroy(void)
{
    if(ui_SetupScreen) lv_obj_del(ui_SetupScreen);

    // NULL screen variables
    uic_SetupScreen = NULL;
    ui_SetupScreen = NULL;
    uic_HomeButton = NULL;
    ui_HomeButton = NULL;
    uic_CalibrationButton = NULL;
    ui_CalibrationButton = NULL;
    uic_CalibrationButtonText = NULL;
    ui_CalibrationButtonText = NULL;
    uic_DatabaseButton = NULL;
    ui_DatabaseButton = NULL;
    uic_DatabaseButtonText = NULL;
    ui_DatabaseButtonText = NULL;

}
