// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_StationRollerSelected;
lv_obj_t * uic_StationRoller;
lv_obj_t * uic_StationSelectScreen;
lv_obj_t * ui_StationSelectScreen = NULL;
lv_obj_t * ui_StationRoller = NULL;
lv_obj_t * ui_HomeButton5 = NULL;
lv_obj_t * ui_StationRollerHeader = NULL;
lv_obj_t * ui_StationRollerComment = NULL;
lv_obj_t * ui_StationRollerSelected = NULL;
// event funtions
void ui_event_StationRoller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        StationRollPressed(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        StationRollVal(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        StationRollClicked(e);
    }
}

void ui_event_HomeButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
        beep(e);
    }
}

// build funtions

void ui_StationSelectScreen_screen_init(void)
{
    ui_StationSelectScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StationSelectScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StationRoller = lv_roller_create(ui_StationSelectScreen);
    lv_roller_set_options(ui_StationRoller, "NO STATIONS", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_StationRoller, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_StationRoller, 480);
    lv_obj_set_height(ui_StationRoller, 240);
    lv_obj_set_align(ui_StationRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_StationRoller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StationRoller, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_StationRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StationRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StationRoller, &lv_font_montserrat_42, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_StationRoller, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_StationRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_StationRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_HomeButton5 = lv_img_create(ui_StationSelectScreen);
    lv_img_set_src(ui_HomeButton5, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton5, 0);
    lv_obj_set_y(ui_HomeButton5, 195);
    lv_obj_set_align(ui_HomeButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_HomeButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_StationRollerHeader = lv_label_create(ui_StationSelectScreen);
    lv_obj_set_width(ui_StationRollerHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StationRollerHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StationRollerHeader, 0);
    lv_obj_set_y(ui_StationRollerHeader, -176);
    lv_obj_set_align(ui_StationRollerHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StationRollerHeader, "Select  & Tap");
    lv_obj_set_style_text_align(ui_StationRollerHeader, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StationRollerHeader, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StationRollerComment = lv_label_create(ui_StationSelectScreen);
    lv_obj_set_width(ui_StationRollerComment, 319);
    lv_obj_set_height(ui_StationRollerComment, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StationRollerComment, 0);
    lv_obj_set_y(ui_StationRollerComment, -148);
    lv_obj_set_align(ui_StationRollerComment, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_StationRollerComment, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_StationRollerComment, "");
    lv_obj_clear_flag(ui_StationRollerComment, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_text_align(ui_StationRollerComment, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StationRollerComment, &ui_font_font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StationRollerSelected = lv_label_create(ui_StationSelectScreen);
    lv_obj_set_width(ui_StationRollerSelected, LV_SIZE_CONTENT);   /// 319
    lv_obj_set_height(ui_StationRollerSelected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StationRollerSelected, 0);
    lv_obj_set_y(ui_StationRollerSelected, -204);
    lv_obj_set_align(ui_StationRollerSelected, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_StationRollerSelected, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_StationRollerSelected, "0-0");
    lv_obj_clear_flag(ui_StationRollerSelected, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_text_align(ui_StationRollerSelected, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StationRollerSelected, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_StationRoller, ui_event_StationRoller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton5, ui_event_HomeButton5, LV_EVENT_ALL, NULL);
    uic_StationSelectScreen = ui_StationSelectScreen;
    uic_StationRoller = ui_StationRoller;
    uic_StationRollerSelected = ui_StationRollerSelected;

}

void ui_StationSelectScreen_screen_destroy(void)
{
    if(ui_StationSelectScreen) lv_obj_del(ui_StationSelectScreen);

    // NULL screen variables
    uic_StationSelectScreen = NULL;
    ui_StationSelectScreen = NULL;
    uic_StationRoller = NULL;
    ui_StationRoller = NULL;
    ui_HomeButton5 = NULL;
    ui_StationRollerHeader = NULL;
    ui_StationRollerComment = NULL;
    uic_StationRollerSelected = NULL;
    ui_StationRollerSelected = NULL;

}
