// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_YouLiveHere;
lv_obj_t * uic_HomeFlagToStore;
lv_obj_t * uic_SetHomeButtonText;
lv_obj_t * uic_SetHomeButton;
lv_obj_t * uic_ResetAllButtonText;
lv_obj_t * uic_ResetAll;
lv_obj_t * uic_DatabaseButtonText;
lv_obj_t * uic_DatabaseButton;
lv_obj_t * uic_CalibrationButtonText;
lv_obj_t * uic_CalibrationButton;
lv_obj_t * uic_HomeButton;
lv_obj_t * uic_SetupScreen;
lv_obj_t * ui_SetupScreen = NULL;
lv_obj_t * ui_HomeButton = NULL;
lv_obj_t * ui_CalibrationButton = NULL;
lv_obj_t * ui_CalibrationButtonText = NULL;
lv_obj_t * ui_DatabaseButton = NULL;
lv_obj_t * ui_DatabaseButtonText = NULL;
lv_obj_t * ui_ResetAll = NULL;
lv_obj_t * ui_ResetAllButtonText = NULL;
lv_obj_t * ui_SetHomeButton = NULL;
lv_obj_t * ui_SetHomeButtonText = NULL;
lv_obj_t * ui_HomeFlagToStore = NULL;
lv_obj_t * ui_YouLiveHere = NULL;
// event funtions
void ui_event_HomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
        beep(e);
    }
}

void ui_event_CalibrationButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CalibrationEnter(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        CalibrationEnter(e);
    }
}

void ui_event_DatabaseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        DatabaseEnter(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        DatabaseEnter(e);
    }
}

void ui_event_ResetAll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        ResetAllEnter(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ResetAllEnter(e);
    }
}

void ui_event_SetHomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        SetHomeEnter(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        SetHomeEnter(e);
    }
}

// build funtions

void ui_SetupScreen_screen_init(void)
{
    ui_SetupScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetupScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton = lv_img_create(ui_SetupScreen);
    lv_img_set_src(ui_HomeButton, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton, 0);
    lv_obj_set_y(ui_HomeButton, 195);
    lv_obj_set_align(ui_HomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_HomeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_CalibrationButton = lv_btn_create(ui_SetupScreen);
    lv_obj_set_width(ui_CalibrationButton, 200);
    lv_obj_set_height(ui_CalibrationButton, 50);
    lv_obj_set_x(ui_CalibrationButton, -110);
    lv_obj_set_y(ui_CalibrationButton, -70);
    lv_obj_set_align(ui_CalibrationButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CalibrationButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);
    ui_object_set_themeable_style_property(ui_CalibrationButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_green);
    ui_object_set_themeable_style_property(ui_CalibrationButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_green);
    lv_obj_set_style_shadow_width(ui_CalibrationButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_CalibrationButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_CalibrationButtonText = lv_label_create(ui_SetupScreen);
    lv_obj_set_width(ui_CalibrationButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationButtonText, -110);
    lv_obj_set_y(ui_CalibrationButtonText, -70);
    lv_obj_set_align(ui_CalibrationButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationButtonText, "CALIBRATION");
    lv_obj_set_style_text_color(ui_CalibrationButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationButtonText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DatabaseButton = lv_btn_create(ui_SetupScreen);
    lv_obj_set_width(ui_DatabaseButton, 200);
    lv_obj_set_height(ui_DatabaseButton, 50);
    lv_obj_set_x(ui_DatabaseButton, 110);
    lv_obj_set_y(ui_DatabaseButton, -70);
    lv_obj_set_align(ui_DatabaseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DatabaseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DatabaseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DatabaseButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_DatabaseButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);
    ui_object_set_themeable_style_property(ui_DatabaseButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_green);
    ui_object_set_themeable_style_property(ui_DatabaseButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_green);
    lv_obj_set_style_shadow_width(ui_DatabaseButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_DatabaseButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_DatabaseButtonText = lv_label_create(ui_SetupScreen);
    lv_obj_set_width(ui_DatabaseButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DatabaseButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DatabaseButtonText, 110);
    lv_obj_set_y(ui_DatabaseButtonText, -70);
    lv_obj_set_align(ui_DatabaseButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DatabaseButtonText, "DATABASE");
    lv_obj_set_style_text_color(ui_DatabaseButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DatabaseButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DatabaseButtonText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetAll = lv_btn_create(ui_SetupScreen);
    lv_obj_set_width(ui_ResetAll, 200);
    lv_obj_set_height(ui_ResetAll, 50);
    lv_obj_set_x(ui_ResetAll, -110);
    lv_obj_set_y(ui_ResetAll, 0);
    lv_obj_set_align(ui_ResetAll, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetAll, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetAll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ResetAll, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_ResetAll, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);
    ui_object_set_themeable_style_property(ui_ResetAll, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_red);
    ui_object_set_themeable_style_property(ui_ResetAll, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_red);
    lv_obj_set_style_shadow_width(ui_ResetAll, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ResetAll, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ResetAllButtonText = lv_label_create(ui_SetupScreen);
    lv_obj_set_width(ui_ResetAllButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetAllButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResetAllButtonText, -110);
    lv_obj_set_y(ui_ResetAllButtonText, 0);
    lv_obj_set_align(ui_ResetAllButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetAllButtonText, "RESET ALL");
    lv_obj_set_style_text_color(ui_ResetAllButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetAllButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResetAllButtonText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetHomeButton = lv_btn_create(ui_SetupScreen);
    lv_obj_set_width(ui_SetHomeButton, 200);
    lv_obj_set_height(ui_SetHomeButton, 50);
    lv_obj_set_x(ui_SetHomeButton, 110);
    lv_obj_set_y(ui_SetHomeButton, 0);
    lv_obj_set_align(ui_SetHomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetHomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetHomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SetHomeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_SetHomeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);
    ui_object_set_themeable_style_property(ui_SetHomeButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_yellow);
    ui_object_set_themeable_style_property(ui_SetHomeButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_yellow);
    lv_obj_set_style_shadow_width(ui_SetHomeButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_SetHomeButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SetHomeButtonText = lv_label_create(ui_SetupScreen);
    lv_obj_set_width(ui_SetHomeButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetHomeButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetHomeButtonText, 110);
    lv_obj_set_y(ui_SetHomeButtonText, 0);
    lv_obj_set_align(ui_SetHomeButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetHomeButtonText, "SET AS HOME");
    lv_obj_set_style_text_color(ui_SetHomeButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetHomeButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetHomeButtonText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeFlagToStore = lv_img_create(ui_SetupScreen);
    lv_img_set_src(ui_HomeFlagToStore, &ui_img_xx_png);
    lv_obj_set_height(ui_HomeFlagToStore, 72);
    lv_obj_set_width(ui_HomeFlagToStore, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_x(ui_HomeFlagToStore, 0);
    lv_obj_set_y(ui_HomeFlagToStore, -190);
    lv_obj_set_align(ui_HomeFlagToStore, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeFlagToStore, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_HomeFlagToStore,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_HomeFlagToStore, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_HomeFlagToStore, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_HomeFlagToStore, LV_SCROLL_SNAP_CENTER);

    ui_YouLiveHere = lv_label_create(ui_SetupScreen);
    lv_obj_set_width(ui_YouLiveHere, 343);
    lv_obj_set_height(ui_YouLiveHere, 25);
    lv_obj_set_x(ui_YouLiveHere, 0);
    lv_obj_set_y(ui_YouLiveHere, -135);
    lv_obj_set_align(ui_YouLiveHere, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_YouLiveHere, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_YouLiveHere, "YOU LIVE HERE");
    lv_obj_add_flag(ui_YouLiveHere, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_YouLiveHere, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YouLiveHere, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrationButton, ui_event_CalibrationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DatabaseButton, ui_event_DatabaseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetAll, ui_event_ResetAll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetHomeButton, ui_event_SetHomeButton, LV_EVENT_ALL, NULL);
    uic_SetupScreen = ui_SetupScreen;
    uic_HomeButton = ui_HomeButton;
    uic_CalibrationButton = ui_CalibrationButton;
    uic_CalibrationButtonText = ui_CalibrationButtonText;
    uic_DatabaseButton = ui_DatabaseButton;
    uic_DatabaseButtonText = ui_DatabaseButtonText;
    uic_ResetAll = ui_ResetAll;
    uic_ResetAllButtonText = ui_ResetAllButtonText;
    uic_SetHomeButton = ui_SetHomeButton;
    uic_SetHomeButtonText = ui_SetHomeButtonText;
    uic_HomeFlagToStore = ui_HomeFlagToStore;
    uic_YouLiveHere = ui_YouLiveHere;

}

void ui_SetupScreen_screen_destroy(void)
{
    if(ui_SetupScreen) lv_obj_del(ui_SetupScreen);

    // NULL screen variables
    uic_SetupScreen = NULL;
    ui_SetupScreen = NULL;
    uic_HomeButton = NULL;
    ui_HomeButton = NULL;
    uic_CalibrationButton = NULL;
    ui_CalibrationButton = NULL;
    uic_CalibrationButtonText = NULL;
    ui_CalibrationButtonText = NULL;
    uic_DatabaseButton = NULL;
    ui_DatabaseButton = NULL;
    uic_DatabaseButtonText = NULL;
    ui_DatabaseButtonText = NULL;
    uic_ResetAll = NULL;
    ui_ResetAll = NULL;
    uic_ResetAllButtonText = NULL;
    ui_ResetAllButtonText = NULL;
    uic_SetHomeButton = NULL;
    ui_SetHomeButton = NULL;
    uic_SetHomeButtonText = NULL;
    ui_SetHomeButtonText = NULL;
    uic_HomeFlagToStore = NULL;
    ui_HomeFlagToStore = NULL;
    uic_YouLiveHere = NULL;
    ui_YouLiveHere = NULL;

}
