// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETUPSCREEN_H
#define UI_SETUPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SetupScreen
extern void ui_SetupScreen_screen_init(void);
extern void ui_SetupScreen_screen_destroy(void);
extern lv_obj_t * ui_SetupScreen;
extern void ui_event_HomeButton(lv_event_t * e);
extern lv_obj_t * ui_HomeButton;
extern void ui_event_CalibrationButton(lv_event_t * e);
extern lv_obj_t * ui_CalibrationButton;
extern lv_obj_t * ui_CalibrationButtonText;
extern void ui_event_DatabaseButton(lv_event_t * e);
extern lv_obj_t * ui_DatabaseButton;
extern lv_obj_t * ui_DatabaseButtonText;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SetupScreen;
extern lv_obj_t * uic_HomeButton;
extern lv_obj_t * uic_CalibrationButton;
extern lv_obj_t * uic_CalibrationButtonText;
extern lv_obj_t * uic_DatabaseButton;
extern lv_obj_t * uic_DatabaseButtonText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

