// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_SaveToneVolText;
lv_obj_t * uic_ToneControlInstruction;
lv_obj_t * uic_SaveToneVol;
lv_obj_t * uic_Text_Treble;
lv_obj_t * uic_Text_Bass;
lv_obj_t * uic_TrebleValue;
lv_obj_t * uic_TrebleArc;
lv_obj_t * uic_BassValue;
lv_obj_t * uic_BassArc;
lv_obj_t * uic_ToneControlScreen;
lv_obj_t * ui_ToneControlScreen = NULL;
lv_obj_t * ui_BassArc = NULL;
lv_obj_t * ui_BassValue = NULL;
lv_obj_t * ui_TrebleArc = NULL;
lv_obj_t * ui_TrebleValue = NULL;
lv_obj_t * ui_HomeButton7 = NULL;
lv_obj_t * ui_Text_Bass = NULL;
lv_obj_t * ui_Text_Treble = NULL;
lv_obj_t * ui_SaveToneVol = NULL;
lv_obj_t * ui_ToneControlInstruction = NULL;
lv_obj_t * ui_SaveToneVolText = NULL;
// event funtions
void ui_event_BassArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_BassValue, target, "", "");
    }
}

void ui_event_TrebleArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_TrebleValue, target, "", "");
    }
}

void ui_event_HomeButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
        beep(e);
    }
}

void ui_event_SaveToneVol(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        SaveVolTone(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        SaveVolTone(e);
    }
}

// build funtions

void ui_ToneControlScreen_screen_init(void)
{
    ui_ToneControlScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ToneControlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BassArc = lv_arc_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_BassArc, 200);
    lv_obj_set_height(ui_BassArc, 200);
    lv_obj_set_x(ui_BassArc, -120);
    lv_obj_set_y(ui_BassArc, 30);
    lv_obj_set_align(ui_BassArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_BassArc, 50);

    lv_obj_set_style_arc_color(ui_BassArc, lv_color_hex(0xFBFF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BassArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BassArc, lv_color_hex(0xF1FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BassArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BassValue = lv_label_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_BassValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BassValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BassValue, -120);
    lv_obj_set_y(ui_BassValue, 30);
    lv_obj_set_align(ui_BassValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BassValue, "50");
    lv_obj_set_style_text_color(ui_BassValue, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BassValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BassValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BassValue, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_TrebleArc = lv_arc_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_TrebleArc, 200);
    lv_obj_set_height(ui_TrebleArc, 200);
    lv_obj_set_x(ui_TrebleArc, 120);
    lv_obj_set_y(ui_TrebleArc, 30);
    lv_obj_set_align(ui_TrebleArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_TrebleArc, 50);

    lv_obj_set_style_arc_color(ui_TrebleArc, lv_color_hex(0xFBFF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TrebleArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TrebleArc, lv_color_hex(0xF1FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TrebleArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TrebleValue = lv_label_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_TrebleValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrebleValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrebleValue, 120);
    lv_obj_set_y(ui_TrebleValue, 30);
    lv_obj_set_align(ui_TrebleValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrebleValue, "50");
    lv_obj_set_style_text_color(ui_TrebleValue, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrebleValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrebleValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_TrebleValue, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_HomeButton7 = lv_img_create(ui_ToneControlScreen);
    lv_img_set_src(ui_HomeButton7, &ui_img_home_png);
    lv_obj_set_width(ui_HomeButton7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButton7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeButton7, 0);
    lv_obj_set_y(ui_HomeButton7, 195);
    lv_obj_set_align(ui_HomeButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeButton7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeButton7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_HomeButton7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_Text_Bass = lv_label_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_Text_Bass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Bass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Bass, -120);
    lv_obj_set_y(ui_Text_Bass, 100);
    lv_obj_set_align(ui_Text_Bass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Bass, "BASS");
    lv_obj_set_style_text_color(ui_Text_Bass, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Bass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text_Bass, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text_Treble = lv_label_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_Text_Treble, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text_Treble, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text_Treble, 120);
    lv_obj_set_y(ui_Text_Treble, 100);
    lv_obj_set_align(ui_Text_Treble, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text_Treble, "TREBLE");
    lv_obj_set_style_text_color(ui_Text_Treble, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text_Treble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text_Treble, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveToneVol = lv_btn_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_SaveToneVol, 200);
    lv_obj_set_height(ui_SaveToneVol, 50);
    lv_obj_set_x(ui_SaveToneVol, 0);
    lv_obj_set_y(ui_SaveToneVol, -160);
    lv_obj_set_align(ui_SaveToneVol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveToneVol, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveToneVol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SaveToneVol, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_turquoise);
    ui_object_set_themeable_style_property(ui_SaveToneVol, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_turquoise);

    ui_ToneControlInstruction = lv_label_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_ToneControlInstruction, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_ToneControlInstruction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ToneControlInstruction, 0);
    lv_obj_set_y(ui_ToneControlInstruction, -110);
    lv_obj_set_align(ui_ToneControlInstruction, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ToneControlInstruction, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ToneControlInstruction, "Long Press Button To Save");
    lv_obj_set_style_text_font(ui_ToneControlInstruction, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveToneVolText = lv_label_create(ui_ToneControlScreen);
    lv_obj_set_width(ui_SaveToneVolText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveToneVolText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveToneVolText, 0);
    lv_obj_set_y(ui_SaveToneVolText, -160);
    lv_obj_set_align(ui_SaveToneVolText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveToneVolText, "SAVE THIS");
    lv_obj_set_style_text_color(ui_SaveToneVolText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveToneVolText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveToneVolText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BassArc, ui_event_BassArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TrebleArc, ui_event_TrebleArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton7, ui_event_HomeButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveToneVol, ui_event_SaveToneVol, LV_EVENT_ALL, NULL);
    uic_ToneControlScreen = ui_ToneControlScreen;
    uic_BassArc = ui_BassArc;
    uic_BassValue = ui_BassValue;
    uic_TrebleArc = ui_TrebleArc;
    uic_TrebleValue = ui_TrebleValue;
    uic_Text_Bass = ui_Text_Bass;
    uic_Text_Treble = ui_Text_Treble;
    uic_SaveToneVol = ui_SaveToneVol;
    uic_ToneControlInstruction = ui_ToneControlInstruction;
    uic_SaveToneVolText = ui_SaveToneVolText;

}

void ui_ToneControlScreen_screen_destroy(void)
{
    if(ui_ToneControlScreen) lv_obj_del(ui_ToneControlScreen);

    // NULL screen variables
    uic_ToneControlScreen = NULL;
    ui_ToneControlScreen = NULL;
    uic_BassArc = NULL;
    ui_BassArc = NULL;
    uic_BassValue = NULL;
    ui_BassValue = NULL;
    uic_TrebleArc = NULL;
    ui_TrebleArc = NULL;
    uic_TrebleValue = NULL;
    ui_TrebleValue = NULL;
    ui_HomeButton7 = NULL;
    uic_Text_Bass = NULL;
    ui_Text_Bass = NULL;
    uic_Text_Treble = NULL;
    ui_Text_Treble = NULL;
    uic_SaveToneVol = NULL;
    ui_SaveToneVol = NULL;
    uic_ToneControlInstruction = NULL;
    ui_ToneControlInstruction = NULL;
    uic_SaveToneVolText = NULL;
    ui_SaveToneVolText = NULL;

}
