// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CLOCKSCREEN_H
#define UI_CLOCKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ClockScreen
extern void ui_ClockScreen_screen_init(void);
extern void ui_ClockScreen_screen_destroy(void);
extern void ui_event_ClockScreen(lv_event_t * e);
extern lv_obj_t * ui_ClockScreen;
extern void ui_event_ClockFace(lv_event_t * e);
extern lv_obj_t * ui_ClockFace;
extern void ui_event_ClockFlag(lv_event_t * e);
extern lv_obj_t * ui_ClockFlag;
extern void ui_event_Clock_Power_Off_Icon(lv_event_t * e);
extern lv_obj_t * ui_Clock_Power_Off_Icon;
extern lv_obj_t * ui_Clock_Country;
extern lv_obj_t * ui_Time_Zone_Clock;
extern lv_obj_t * ui_HourHand;
extern lv_obj_t * ui_MinuteHand;
extern lv_obj_t * ui_SecondHand;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ClockScreen;
extern lv_obj_t * uic_ClockFace;
extern lv_obj_t * uic_ClockFlag;
extern lv_obj_t * uic_Clock_Power_Off_Icon;
extern lv_obj_t * uic_Clock_Country;
extern lv_obj_t * uic_Time_Zone_Clock;
extern lv_obj_t * uic_HourHand;
extern lv_obj_t * uic_MinuteHand;
extern lv_obj_t * uic_SecondHand;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

