// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnMainScreenUnLoaded(lv_event_t * e);
void SwitchToClock(lv_event_t * e);
void RadioGlobeClick(lv_event_t * e);
void beep(lv_event_t * e);
void SetupEnter(lv_event_t * e);
void PowerCycle(lv_event_t * e);
void StationInfo(lv_event_t * e);
void RadarScreenOn(lv_event_t * e);
void JukeboxClicked(lv_event_t * e);
void CalibrationEnter(lv_event_t * e);
void DatabaseEnter(lv_event_t * e);
void ResetAllEnter(lv_event_t * e);
void SetHomeEnter(lv_event_t * e);
void CalibrationSetAsZero(lv_event_t * e);
void CalibrationLatitudes(lv_event_t * e);
void CalibrationLongitudes(lv_event_t * e);
void CalibrationAdvanced(lv_event_t * e);
void RebuildDatabase(lv_event_t * e);
void MapClicked(lv_event_t * e);
void click1(lv_event_t * e);
void click2(lv_event_t * e);
void click3(lv_event_t * e);
void click4(lv_event_t * e);
void click5(lv_event_t * e);
void SerialNumberButton(lv_event_t * e);
void StationRollPressed(lv_event_t * e);
void StationRollVal(lv_event_t * e);
void StationRollClicked(lv_event_t * e);
void station1(lv_event_t * e);
void station2(lv_event_t * e);
void station3(lv_event_t * e);
void station4(lv_event_t * e);
void SaveVolTone(lv_event_t * e);
void SpeakerToggle(lv_event_t * e);
void BlueToothToggle(lv_event_t * e);
void CalibratePoint(lv_event_t * e);
void RollerNSorEWChanged(lv_event_t * e);
void OnClockScreenLoad(lv_event_t * e);
void ClockFaceClick(lv_event_t * e);
void ClockFlagToggle(lv_event_t * e);
void ClockHomePower(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
