// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_FAVORITES_H
#define UI_FAVORITES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Favorites
extern void ui_Favorites_screen_init(void);
extern void ui_Favorites_screen_destroy(void);
extern lv_obj_t * ui_Favorites;
extern void ui_event_StationPreset1(lv_event_t * e);
extern lv_obj_t * ui_StationPreset1;
extern void ui_event_StationPreset2(lv_event_t * e);
extern lv_obj_t * ui_StationPreset2;
extern void ui_event_StationPreset3(lv_event_t * e);
extern lv_obj_t * ui_StationPreset3;
extern void ui_event_StationPreset4(lv_event_t * e);
extern lv_obj_t * ui_StationPreset4;
extern void ui_event_FavoritesHomeButton(lv_event_t * e);
extern lv_obj_t * ui_FavoritesHomeButton;
extern lv_obj_t * ui_StationPresetName1;
extern lv_obj_t * ui_StationPresetName2;
extern lv_obj_t * ui_StationPresetName3;
extern lv_obj_t * ui_StationPresetName4;
extern lv_obj_t * ui_ScreenTitle;
extern lv_obj_t * ui_FavoritesStoreHint;
extern lv_obj_t * ui_led1;
extern lv_obj_t * ui_led2;
extern lv_obj_t * ui_led3;
extern lv_obj_t * ui_led4;
extern lv_obj_t * ui_IconWifi;
extern lv_obj_t * ui_GlobeRSSI;
extern lv_obj_t * ui_MemoryText;
extern lv_obj_t * ui_IconMemory;
extern lv_obj_t * ui_MemoryUsage;
extern lv_obj_t * ui_IconSdCard;
extern lv_obj_t * ui_IconBattery;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Favorites;
extern lv_obj_t * uic_StationPreset1;
extern lv_obj_t * uic_StationPreset2;
extern lv_obj_t * uic_StationPreset3;
extern lv_obj_t * uic_StationPreset4;
extern lv_obj_t * uic_FavoritesHomeButton;
extern lv_obj_t * uic_StationPresetName1;
extern lv_obj_t * uic_StationPresetName2;
extern lv_obj_t * uic_StationPresetName3;
extern lv_obj_t * uic_StationPresetName4;
extern lv_obj_t * uic_ScreenTitle;
extern lv_obj_t * uic_FavoritesStoreHint;
extern lv_obj_t * uic_led1;
extern lv_obj_t * uic_led2;
extern lv_obj_t * uic_led3;
extern lv_obj_t * uic_led4;
extern lv_obj_t * uic_GlobeRSSI;
extern lv_obj_t * uic_MemoryUsage;
extern lv_obj_t * uic_IconSdCard;
extern lv_obj_t * uic_IconBattery;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

