// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern void ui_event_HomeGps(lv_event_t * e);
extern lv_obj_t * ui_HomeGps;
extern void ui_event_Local_Time(lv_event_t * e);
extern lv_obj_t * ui_Local_Time;
extern void ui_event_Time_Zone(lv_event_t * e);
extern lv_obj_t * ui_Time_Zone;
extern void ui_event_Text_Radio_Globe(lv_event_t * e);
extern lv_obj_t * ui_Text_Radio_Globe;
extern lv_obj_t * ui_Station_Name;
extern lv_obj_t * ui_Status_Line;
extern lv_obj_t * ui_Station_Title;
extern lv_obj_t * ui_VolumeValue;
extern void ui_event_VolumeArc(lv_event_t * e);
extern lv_obj_t * ui_VolumeArc;
extern void ui_event_SettingButton(lv_event_t * e);
extern lv_obj_t * ui_SettingButton;
extern lv_obj_t * ui_Battery_Icon_Low;
extern lv_obj_t * ui_Battery_Icon_Medium;
extern lv_obj_t * ui_Battery_Icon_High;
extern lv_obj_t * ui_BatteryVoltage;
extern void ui_event_Home_Power_Off_Icon(lv_event_t * e);
extern lv_obj_t * ui_Home_Power_Off_Icon;
extern void ui_event_Home_Flag(lv_event_t * e);
extern lv_obj_t * ui_Home_Flag;
extern lv_obj_t * ui_Home_City;
extern lv_obj_t * ui_Home_Country;
extern lv_obj_t * ui_Weather_Icon;
extern lv_obj_t * ui_Weather_Temperature;
extern lv_obj_t * ui_Weather_Humidity;
extern void ui_event_arrowleft(lv_event_t * e);
extern lv_obj_t * ui_arrowleft;
extern void ui_event_arrowright(lv_event_t * e);
extern lv_obj_t * ui_arrowright;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Home;
extern lv_obj_t * uic_HomeGps;
extern lv_obj_t * uic_Local_Time;
extern lv_obj_t * uic_Time_Zone;
extern lv_obj_t * uic_Station_Name;
extern lv_obj_t * uic_Status_Line;
extern lv_obj_t * uic_Station_Title;
extern lv_obj_t * uic_VolumeValue;
extern lv_obj_t * uic_VolumeArc;
extern lv_obj_t * uic_SettingButton;
extern lv_obj_t * uic_Battery_Icon_Low;
extern lv_obj_t * uic_Battery_Icon_Medium;
extern lv_obj_t * uic_Battery_Icon_High;
extern lv_obj_t * uic_BatteryVoltage;
extern lv_obj_t * uic_Home_Power_Off_Icon;
extern lv_obj_t * uic_Home_Flag;
extern lv_obj_t * uic_Home_City;
extern lv_obj_t * uic_Home_Country;
extern lv_obj_t * uic_Weather_Icon;
extern lv_obj_t * uic_Weather_Temperature;
extern lv_obj_t * uic_Weather_Humidity;
extern lv_obj_t * uic_arrowleft;
extern lv_obj_t * uic_arrowright;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

