// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PASSWORDSCREEN_H
#define UI_PASSWORDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PasswordScreen
extern void ui_PasswordScreen_screen_init(void);
extern void ui_PasswordScreen_screen_destroy(void);
extern lv_obj_t * ui_PasswordScreen;
extern void ui_event_pass1(lv_event_t * e);
extern lv_obj_t * ui_pass1;
extern void ui_event_pass2(lv_event_t * e);
extern lv_obj_t * ui_pass2;
extern void ui_event_pass3(lv_event_t * e);
extern lv_obj_t * ui_pass3;
extern void ui_event_pass4(lv_event_t * e);
extern lv_obj_t * ui_pass4;
extern void ui_event_pass5(lv_event_t * e);
extern lv_obj_t * ui_pass5;
extern void ui_event_HomeButton4(lv_event_t * e);
extern lv_obj_t * ui_HomeButton4;
extern lv_obj_t * ui_CharG;
extern lv_obj_t * ui_CharL;
extern lv_obj_t * ui_CharO;
extern lv_obj_t * ui_CharB;
extern lv_obj_t * ui_CharE;
extern lv_obj_t * ui_Title1;
extern lv_obj_t * ui_lockstatus;
extern lv_obj_t * ui_PuckMac;
extern lv_obj_t * ui_GlobeMac;
extern lv_obj_t * ui_PuckBuild;
extern lv_obj_t * ui_GlobeBuild;
extern void ui_event_SerialNumberButton(lv_event_t * e);
extern lv_obj_t * ui_SerialNumberButton;
extern lv_obj_t * ui_SerialNumberText;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PasswordScreen;
extern lv_obj_t * uic_pass1;
extern lv_obj_t * uic_PuckMac;
extern lv_obj_t * uic_GlobeMac;
extern lv_obj_t * uic_PuckBuild;
extern lv_obj_t * uic_GlobeBuild;
extern lv_obj_t * uic_SerialNumberButton;
extern lv_obj_t * uic_SerialNumberText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

