// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TONECONTROLSCREEN_H
#define UI_TONECONTROLSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ToneControlScreen
extern void ui_ToneControlScreen_screen_init(void);
extern void ui_ToneControlScreen_screen_destroy(void);
extern lv_obj_t * ui_ToneControlScreen;
extern void ui_event_BassArc(lv_event_t * e);
extern lv_obj_t * ui_BassArc;
extern lv_obj_t * ui_BassValue;
extern void ui_event_TrebleArc(lv_event_t * e);
extern lv_obj_t * ui_TrebleArc;
extern lv_obj_t * ui_TrebleValue;
extern void ui_event_HomeButton7(lv_event_t * e);
extern lv_obj_t * ui_HomeButton7;
extern lv_obj_t * ui_Text_Treble;
extern void ui_event_SaveToneVol(lv_event_t * e);
extern lv_obj_t * ui_SaveToneVol;
extern lv_obj_t * ui_SaveToneVolText;
extern void ui_event_InternalSpeaker(lv_event_t * e);
extern lv_obj_t * ui_InternalSpeaker;
extern void ui_event_bluetoothswitch(lv_event_t * e);
extern lv_obj_t * ui_bluetoothswitch;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ledmqtt;
extern lv_obj_t * ui_speakeron;
extern lv_obj_t * ui_speakeroff;
extern lv_obj_t * ui_bluetoothon;
extern lv_obj_t * ui_bluetoothoff;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ToneControlScreen;
extern lv_obj_t * uic_BassArc;
extern lv_obj_t * uic_BassValue;
extern lv_obj_t * uic_TrebleArc;
extern lv_obj_t * uic_TrebleValue;
extern lv_obj_t * uic_Text_Treble;
extern lv_obj_t * uic_SaveToneVol;
extern lv_obj_t * uic_SaveToneVolText;
extern lv_obj_t * uic_InternalSpeaker;
extern lv_obj_t * uic_bluetoothswitch;
extern lv_obj_t * uic_ledmqtt;
extern lv_obj_t * uic_speakeron;
extern lv_obj_t * uic_speakeroff;
extern lv_obj_t * uic_bluetoothon;
extern lv_obj_t * uic_bluetoothoff;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

