// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_SecondHand;
lv_obj_t * uic_MinuteHand;
lv_obj_t * uic_HourHand;
lv_obj_t * uic_Time_Zone_Clock;
lv_obj_t * uic_Clock_Country;
lv_obj_t * uic_Clock_Power_Off_Icon;
lv_obj_t * uic_ClockFlag;
lv_obj_t * uic_ClockFace;
lv_obj_t * uic_ClockScreen;
lv_obj_t * ui_ClockScreen = NULL;
lv_obj_t * ui_ClockFace = NULL;
lv_obj_t * ui_ClockFlag = NULL;
lv_obj_t * ui_Clock_Power_Off_Icon = NULL;
lv_obj_t * ui_Clock_Country = NULL;
lv_obj_t * ui_Time_Zone_Clock = NULL;
lv_obj_t * ui_HourHand = NULL;
lv_obj_t * ui_MinuteHand = NULL;
lv_obj_t * ui_SecondHand = NULL;
// event funtions
void ui_event_ClockFace(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ClockFaceClick(e);
    }
}

void ui_event_ClockFlag(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ClockFlagToggle(e);
    }
}

void ui_event_Clock_Power_Off_Icon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ClockHomePower(e);
    }
}

// build funtions

void ui_ClockScreen_screen_init(void)
{
    ui_ClockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ClockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockFace = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_ClockFace, &ui_img_clock480_png);
    lv_obj_set_width(ui_ClockFace, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockFace, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ClockFace, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClockFace, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ClockFace, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockFlag = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_ClockFlag, &ui_img_xx_png);
    lv_obj_set_width(ui_ClockFlag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockFlag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockFlag, 0);
    lv_obj_set_y(ui_ClockFlag, -140);
    lv_obj_set_align(ui_ClockFlag, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClockFlag, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ClockFlag, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_ClockFlag, 192);
    lv_obj_set_scrollbar_mode(ui_ClockFlag, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_ClockFlag, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_ClockFlag, LV_SCROLL_SNAP_CENTER);

    ui_Clock_Power_Off_Icon = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_Clock_Power_Off_Icon, &ui_img_power75x75_png);
    lv_obj_set_width(ui_Clock_Power_Off_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Power_Off_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock_Power_Off_Icon, 0);
    lv_obj_set_y(ui_Clock_Power_Off_Icon, 165);
    lv_obj_set_align(ui_Clock_Power_Off_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Clock_Power_Off_Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Clock_Power_Off_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Clock_Power_Off_Icon, 196);
    ui_object_set_themeable_style_property(ui_Clock_Power_Off_Icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_red);
    ui_object_set_themeable_style_property(ui_Clock_Power_Off_Icon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_red);

    ui_Clock_Country = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Clock_Country, 318);
    lv_obj_set_height(ui_Clock_Country, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock_Country, 0);
    lv_obj_set_y(ui_Clock_Country, -90);
    lv_obj_set_align(ui_Clock_Country, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Clock_Country, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Clock_Country, "NETHERLANDS");
    lv_obj_set_style_text_color(ui_Clock_Country, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clock_Country, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Clock_Country, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Clock_Country, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Clock_Country, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock_Country, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_Zone_Clock = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Time_Zone_Clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Zone_Clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Zone_Clock, 0);
    lv_obj_set_y(ui_Time_Zone_Clock, 95);
    lv_obj_set_align(ui_Time_Zone_Clock, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Time_Zone_Clock, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Time_Zone_Clock, "TIME ZONE\nDATE\nPARTOFDAY");
    lv_obj_set_style_text_color(ui_Time_Zone_Clock, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time_Zone_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Time_Zone_Clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Time_Zone_Clock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Time_Zone_Clock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_Zone_Clock, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourHand = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_HourHand, &ui_img_hour_hand_png);
    lv_obj_set_width(ui_HourHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourHand, 0);
    lv_obj_set_y(ui_HourHand, -45);
    lv_obj_set_align(ui_HourHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HourHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HourHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_HourHand, 18, 138);
    lv_img_set_angle(ui_HourHand, 2700);
    lv_img_set_zoom(ui_HourHand, 275);
    lv_obj_set_style_img_recolor(ui_HourHand, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_HourHand, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinuteHand = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_MinuteHand, &ui_img_minute_hand_png);
    lv_obj_set_width(ui_MinuteHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinuteHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteHand, 0);
    lv_obj_set_y(ui_MinuteHand, -99);
    lv_obj_set_align(ui_MinuteHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinuteHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MinuteHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_MinuteHand, 18, 255);
    lv_img_set_angle(ui_MinuteHand, 3000);
    lv_img_set_zoom(ui_MinuteHand, 190);
    lv_obj_set_style_img_recolor(ui_MinuteHand, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_MinuteHand, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondHand = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_SecondHand, &ui_img_second_hand_png);
    lv_obj_set_width(ui_SecondHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecondHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SecondHand, -1);
    lv_obj_set_y(ui_SecondHand, -37);
    lv_obj_set_align(ui_SecondHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SecondHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SecondHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_SecondHand, 11, 215);
    lv_img_set_angle(ui_SecondHand, 1020);
    lv_img_set_zoom(ui_SecondHand, 240);

    lv_obj_add_event_cb(ui_ClockFace, ui_event_ClockFace, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClockFlag, ui_event_ClockFlag, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Clock_Power_Off_Icon, ui_event_Clock_Power_Off_Icon, LV_EVENT_ALL, NULL);
    uic_ClockScreen = ui_ClockScreen;
    uic_ClockFace = ui_ClockFace;
    uic_ClockFlag = ui_ClockFlag;
    uic_Clock_Power_Off_Icon = ui_Clock_Power_Off_Icon;
    uic_Clock_Country = ui_Clock_Country;
    uic_Time_Zone_Clock = ui_Time_Zone_Clock;
    uic_HourHand = ui_HourHand;
    uic_MinuteHand = ui_MinuteHand;
    uic_SecondHand = ui_SecondHand;

}

void ui_ClockScreen_screen_destroy(void)
{
    if(ui_ClockScreen) lv_obj_del(ui_ClockScreen);

    // NULL screen variables
    uic_ClockScreen = NULL;
    ui_ClockScreen = NULL;
    uic_ClockFace = NULL;
    ui_ClockFace = NULL;
    uic_ClockFlag = NULL;
    ui_ClockFlag = NULL;
    uic_Clock_Power_Off_Icon = NULL;
    ui_Clock_Power_Off_Icon = NULL;
    uic_Clock_Country = NULL;
    ui_Clock_Country = NULL;
    uic_Time_Zone_Clock = NULL;
    ui_Time_Zone_Clock = NULL;
    uic_HourHand = NULL;
    ui_HourHand = NULL;
    uic_MinuteHand = NULL;
    ui_MinuteHand = NULL;
    uic_SecondHand = NULL;
    ui_SecondHand = NULL;

}
